# Projet KAYAK

In [ ]:
# list of project city 
city_list = ["Mont Saint Michel",
"Saint Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]

In [39]:
# import librairies
import requests, time, csv, os, json, uuid
import pandas as pd 
from dotenv import load_dotenv

# 1. Data Extraction

## 1.1 Weather data

### 1.1.1 Get GPS data for city list

In [3]:
def get_coordinates(city_name):
    """
    Return latitude and longitude of the city
    """

    URL_NOMINATIM = "https://nominatim.openstreetmap.org/search"
    params = {
    "q": city_name,
    "format": "json"
    }
    headers = {
        'User-Agent': 'MyPythonScript/1.0',
        'Referer': 'https://mywebsite.com/page.html'
    }          


    try:
        response = requests.get(URL_NOMINATIM, params=params, headers=headers)
        response.raise_for_status()  # Raise an exception for non-200 status codes

        data = response.json()

        if len(data) == 0:
            print("City not found")
            return None # Return None to indicate unsuccessful retrieval
       
        latitude = data[0]['lat']
        longitude = data[0]['lon']
        return [latitude, longitude]
  
    except requests.exceptions.RequestException as e:
        print(f"Failed to retrieve data: {e}")
        return None # Return None to indicate unsuccessful retrieval

In [ ]:
city_data = []
for city in city_list:
    city_coordinates = get_coordinates(city)
    current_city = {'city_name': city, "coordinates": city_coordinates}
    #print(current_city)
    city_data.append(current_city)
    time.sleep(1) # Timer to avoid overloading the API 

print(city_data)

[{'city_name': 'Mont Saint Michel', 'coordinates': ['48.6359541', '-1.5114600']}, {'city_name': 'Saint Malo', 'coordinates': ['48.6495180', '-2.0260409']}, {'city_name': 'Bayeux', 'coordinates': ['49.2764624', '-0.7024738']}, {'city_name': 'Le Havre', 'coordinates': ['49.4938975', '0.1079732']}, {'city_name': 'Rouen', 'coordinates': ['49.4404591', '1.0939658']}, {'city_name': 'Paris', 'coordinates': ['48.8588897', '2.3200410']}, {'city_name': 'Amiens', 'coordinates': ['49.8941708', '2.2956951']}, {'city_name': 'Lille', 'coordinates': ['50.6365654', '3.0635282']}, {'city_name': 'Strasbourg', 'coordinates': ['48.5846140', '7.7507127']}, {'city_name': 'Chateau du Haut Koenigsbourg', 'coordinates': ['48.2494107', '7.3443202']}, {'city_name': 'Colmar', 'coordinates': ['48.0777517', '7.3579641']}, {'city_name': 'Eguisheim', 'coordinates': ['48.0447968', '7.3079618']}, {'city_name': 'Besancon', 'coordinates': ['47.2380222', '6.0243622']}, {'city_name': 'Dijon', 'coordinates': ['47.3215806', '5.0414701']}, {'city_name': 'Annecy', 'coordinates': ['45.8992348', '6.1288847']}, {'city_name': 'Grenoble', 'coordinates': ['45.1875602', '5.7357819']}, {'city_name': 'Lyon', 'coordinates': ['45.7578137', '4.8320114']}, {'city_name': 'Gorges du Verdon', 'coordinates': ['43.7496562', '6.3285616']}, {'city_name': 'Bormes les Mimosas', 'coordinates': ['43.1506968', '6.3419285']}, {'city_name': 'Cassis', 'coordinates': ['43.2140359', '5.5396318']}, {'city_name': 'Marseille', 'coordinates': ['43.2961743', '5.3699525']}, {'city_name': 'Aix en Provence', 'coordinates': ['43.5298424', '5.4474738']}, {'city_name': 'Avignon', 'coordinates': ['43.9492493', '4.8059012']}, {'city_name': 'Uzes', 'coordinates': ['44.0121279', '4.4196718']}, {'city_name': 'Nimes', 'coordinates': ['43.8374249', '4.3600687']}, {'city_name': 'Aigues Mortes', 'coordinates': ['43.5661521', '4.1915400']}, {'city_name': 'Saintes Maries de la mer', 'coordinates': ['43.4515922', '4.4277202']}, {'city_name': 'Collioure', 'coordinates': ['42.5250500', '3.0831554']}, {'city_name': 'Carcassonne', 'coordinates': ['43.2130358', '2.3491069']}, {'city_name': 'Ariege', 'coordinates': ['42.9455368', '1.4065544']}, {'city_name': 'Toulouse', 'coordinates': ['43.6044622', '1.4442469']}, {'city_name': 'Montauban', 'coordinates': ['44.0175835', '1.3549991']}, {'city_name': 'Biarritz', 'coordinates': ['43.4711437', '-1.5527266']}, {'city_name': 'Bayonne', 'coordinates': ['43.4945144', '-1.4736657']}, {'city_name': 'La Rochelle', 'coordinates': ['46.1597320', '-1.1515951']}]

In [5]:
# test uuid to get unique id
id = uuid.uuid4()
print(id)

af191b6c-8199-4d05-a1d9-854e175dcf28

In [ ]:
# directory path for saved file
directory = "data"

# make directory if not exist
os.makedirs(directory, exist_ok=True)

# full path to the CSV file
file_path = os.path.join(directory, "cities_data.csv")

# create CSV file et write data
with open(file_path, 'w', newline='') as csvfile:
    # Add id column
    fieldnames = ['id', 'city_name', 'latitude', 'longitude']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()

    # create CSV data and add uuid 
    for city in city_data:
        writer.writerow({'id': str(uuid.uuid4()), 'city_name': city['city_name'], 'latitude': city['coordinates'][0], 'longitude': city['coordinates'][1]})


print("The CSV file was successfully created in the data folder, with a unique 'id' column.")

The CSV file was successfully created in the data folder, with a unique 'id' column.

### 1.1.2 Get weather data for city list

In [40]:
# Load the .env file 
load_dotenv()
API_KEY_WEATHER = os.getenv("API_KEY_WEATHER")
KEYTEST = os.getenv("KEYTEST")
print("KEYTEST", KEYTEST)
# Test Request API weather
weather_url = f"https://api.openweathermap.org/data/2.5/forecast?lat=48.6359541&lon=-1.511459954959514&appid={API_KEY_WEATHER}"
print(weather_url)
response = requests.get(weather_url)
data = response.json()
display(data)

KEYTEST toto
https://api.openweathermap.org/data/2.5/forecast?lat=48.6359541&lon=-1.511459954959514&appid=7dc1deacd8be5a0524b8a54ae585ec6d

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1758121200,
   'main': {'temp': 294.02,
    'feels_like': 293.47,
    'temp_min': 294.02,
    'temp_max': 294.62,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1015,
    'humidity': 50,
    'temp_kf': -0.6},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 9},
   'wind': {'speed': 5.31, 'deg': 245, 'gust': 7.16},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-17 15:00:00'},
  {'dt': 1758132000,
   'main': {'temp': 292.45,
    'feels_like': 292.13,
    'temp_min': 291.81,
    'temp_max': 292.45,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1015,
    'humidity': 65,
    'temp_kf': 0.64},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 5},
   'wind': {'speed': 2.04, 'deg': 273, 'gust': 4.93},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-17 18:00:00'},
  {'dt': 1758142800,
   'main': {'temp': 289.52,
    'feels_like': 289.48,
    'temp_min': 289.52,
    'temp_max': 289.52,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.06, 'deg': 221, 'gust': 5.51},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-17 21:00:00'},
  {'dt': 1758153600,
   'main': {'temp': 288.52,
    'feels_like': 288.59,
    'temp_min': 288.52,
    'temp_max': 288.52,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 95,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.99, 'deg': 214, 'gust': 4.09},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-18 00:00:00'},
  {'dt': 1758164400,
   'main': {'temp': 288.05,
    'feels_like': 288.08,
    'temp_min': 288.05,
    'temp_max': 288.05,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 95,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 3.17, 'deg': 204, 'gust': 4.48},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-18 03:00:00'},
  {'dt': 1758175200,
   'main': {'temp': 287.98,
    'feels_like': 288.03,
    'temp_min': 287.98,
    'temp_max': 287.98,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 96,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 5},
   'wind': {'speed': 3.12, 'deg': 196, 'gust': 4.54},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-18 06:00:00'},
  {'dt': 1758186000,
   'main': {'temp': 291.19,
    'feels_like': 291.16,
    'temp_min': 291.19,
    'temp_max': 291.19,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 52},
   'wind': {'speed': 4.13, 'deg': 214, 'gust': 5.14},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-18 09:00:00'},
  {'dt': 1758196800,
   'main': {'temp': 296.08,
    'feels_like': 296,
    'temp_min': 296.08,
    'temp_max': 296.08,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 60,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 59},
   'wind': {'speed': 2.88, 'deg': 212, 'gust': 4.78},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-18 12:00:00'},
  {'dt': 1758207600,
   'main': {'temp': 299.42,
    'feels_like': 299.42,
    'temp_min': 299.42,
    'temp_max': 299.42,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1015,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 11},
   'wind': {'speed': 2.79, 'deg': 212, 'gust': 5.03},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-18 15:00:00'},
  {'dt': 1758218400,
   'main': {'temp': 294.77,
    'feels_like': 294.53,
    'temp_min': 294.77,
    'temp_max': 294.77,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1015,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 24},
   'wind': {'speed': 0.64, 'deg': 283, 'gust': 1.67},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-18 18:00:00'},
  {'dt': 1758229200,
   'main': {'temp': 290.48,
    'feels_like': 290.25,
    'temp_min': 290.48,
    'temp_max': 290.48,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 76,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 15},
   'wind': {'speed': 1.12, 'deg': 282, 'gust': 1.57},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-18 21:00:00'},
  {'dt': 1758240000,
   'main': {'temp': 289.13,
    'feels_like': 288.95,
    'temp_min': 289.13,
    'temp_max': 289.13,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1016,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 33},
   'wind': {'speed': 2.28, 'deg': 160, 'gust': 2.21},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-19 00:00:00'},
  {'dt': 1758250800,
   'main': {'temp': 288.07,
    'feels_like': 287.65,
    'temp_min': 288.07,
    'temp_max': 288.07,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1015,
    'humidity': 78,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 93},
   'wind': {'speed': 2.7, 'deg': 135, 'gust': 2.82},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-19 03:00:00'},
  {'dt': 1758261600,
   'main': {'temp': 288.47,
    'feels_like': 287.65,
    'temp_min': 288.47,
    'temp_max': 288.47,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1014,
    'humidity': 61,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 84},
   'wind': {'speed': 3.25, 'deg': 143, 'gust': 4.37},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-19 06:00:00'},
  {'dt': 1758272400,
   'main': {'temp': 294.76,
    'feels_like': 293.97,
    'temp_min': 294.76,
    'temp_max': 294.76,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1014,
    'humidity': 38,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.93, 'deg': 158, 'gust': 6.02},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-19 09:00:00'},
  {'dt': 1758283200,
   'main': {'temp': 302.14,
    'feels_like': 300.77,
    'temp_min': 302.14,
    'temp_max': 302.14,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1012,
    'humidity': 25,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 85},
   'wind': {'speed': 5.27, 'deg': 172, 'gust': 7.41},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-19 12:00:00'},
  {'dt': 1758294000,
   'main': {'temp': 304.56,
    'feels_like': 302.88,
    'temp_min': 304.56,
    'temp_max': 304.56,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 25,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 69},
   'wind': {'speed': 4.71, 'deg': 195, 'gust': 6.8},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-19 15:00:00'},
  {'dt': 1758304800,
   'main': {'temp': 298.02,
    'feels_like': 297.69,
    'temp_min': 298.02,
    'temp_max': 298.02,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 43,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 56},
   'wind': {'speed': 3.03, 'deg': 233, 'gust': 4.88},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-19 18:00:00'},
  {'dt': 1758315600,
   'main': {'temp': 293.68,
    'feels_like': 293.51,
    'temp_min': 293.68,
    'temp_max': 293.68,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1011,
    'humidity': 66,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 82},
   'wind': {'speed': 2.7, 'deg': 211, 'gust': 2.55},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-19 21:00:00'},
  {'dt': 1758326400,
   'main': {'temp': 290.18,
    'feels_like': 289.95,
    'temp_min': 290.18,
    'temp_max': 290.18,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 77,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 91},
   'wind': {'speed': 1.29, 'deg': 215, 'gust': 1.36},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-20 00:00:00'},
  {'dt': 1758337200,
   'main': {'temp': 290.34,
    'feels_like': 290.1,
    'temp_min': 290.34,
    'temp_max': 290.34,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1009,
    'humidity': 76,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.91, 'deg': 215, 'gust': 1.94},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-20 03:00:00'},
  {'dt': 1758348000,
   'main': {'temp': 291,
    'feels_like': 290.54,
    'temp_min': 291,
    'temp_max': 291,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 65,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.28, 'deg': 222, 'gust': 1.37},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-20 06:00:00'},
  {'dt': 1758358800,
   'main': {'temp': 292.64,
    'feels_like': 292.32,
    'temp_min': 292.64,
    'temp_max': 292.64,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 64,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.79, 'deg': 177, 'gust': 9.97},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-20 09:00:00'},
  {'dt': 1758369600,
   'main': {'temp': 298.5,
    'feels_like': 298.5,
    'temp_min': 298.5,
    'temp_max': 298.5,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1007,
    'humidity': 54,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 97},
   'wind': {'speed': 8.26, 'deg': 197, 'gust': 11.22},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.22},
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-20 12:00:00'},
  {'dt': 1758380400,
   'main': {'temp': 297.62,
    'feels_like': 297.25,
    'temp_min': 297.62,
    'temp_max': 297.62,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 43,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 7.38, 'deg': 222, 'gust': 9.64},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-20 15:00:00'},
  {'dt': 1758391200,
   'main': {'temp': 294.51,
    'feels_like': 294.27,
    'temp_min': 294.51,
    'temp_max': 294.51,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 60,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.57, 'deg': 240, 'gust': 8.94},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-20 18:00:00'},
  {'dt': 1758402000,
   'main': {'temp': 289.52,
    'feels_like': 289.14,
    'temp_min': 289.52,
    'temp_max': 289.52,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 74,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.42, 'deg': 278, 'gust': 7.52},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-20 21:00:00'},
  {'dt': 1758412800,
   'main': {'temp': 286.31,
    'feels_like': 285.72,
    'temp_min': 286.31,
    'temp_max': 286.31,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 78,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.08, 'deg': 231, 'gust': 9.18},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-21 00:00:00'},
  {'dt': 1758423600,
   'main': {'temp': 284.42,
    'feels_like': 284,
    'temp_min': 284.42,
    'temp_max': 284.42,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 92,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 69},
   'wind': {'speed': 4.33, 'deg': 200, 'gust': 9.32},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-21 03:00:00'},
  {'dt': 1758434400,
   'main': {'temp': 284.59,
    'feels_like': 284.24,
    'temp_min': 284.59,
    'temp_max': 284.59,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1007,
    'humidity': 94,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 34},
   'wind': {'speed': 5.19, 'deg': 193, 'gust': 11.32},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-21 06:00:00'},
  {'dt': 1758445200,
   'main': {'temp': 290.13,
    'feels_like': 289.45,
    'temp_min': 290.13,
    'temp_max': 290.13,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1007,
    'humidity': 60,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 8.45, 'deg': 223, 'gust': 10.8},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-21 09:00:00'},
  {'dt': 1758456000,
   'main': {'temp': 293.27,
    'feels_like': 292.51,
    'temp_min': 293.27,
    'temp_max': 293.27,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 15},
   'wind': {'speed': 8.53, 'deg': 226, 'gust': 10.47},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-21 12:00:00'},
  {'dt': 1758466800,
   'main': {'temp': 288.87,
    'feels_like': 288.3,
    'temp_min': 288.87,
    'temp_max': 288.87,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 69,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 3.06, 'deg': 302, 'gust': 4.61},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.17},
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-21 15:00:00'},
  {'dt': 1758477600,
   'main': {'temp': 287.46,
    'feels_like': 286.9,
    'temp_min': 287.46,
    'temp_max': 287.46,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 75,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 1.28, 'deg': 327, 'gust': 2.91},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.19},
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-21 18:00:00'},
  {'dt': 1758488400,
   'main': {'temp': 285.89,
    'feels_like': 285.15,
    'temp_min': 285.89,
    'temp_max': 285.89,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 74,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 72},
   'wind': {'speed': 4.12, 'deg': 259, 'gust': 6.56},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-21 21:00:00'},
  {'dt': 1758499200,
   'main': {'temp': 282.55,
    'feels_like': 280.56,
    'temp_min': 282.55,
    'temp_max': 282.55,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 49},
   'wind': {'speed': 3.7, 'deg': 233, 'gust': 4.87},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-22 00:00:00'},
  {'dt': 1758510000,
   'main': {'temp': 281.5,
    'feels_like': 279.57,
    'temp_min': 281.5,
    'temp_max': 281.5,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 92,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 21},
   'wind': {'speed': 3.18, 'deg': 208, 'gust': 3.85},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-09-22 03:00:00'},
  {'dt': 1758520800,
   'main': {'temp': 280.63,
    'feels_like': 278.41,
    'temp_min': 280.63,
    'temp_max': 280.63,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 93,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 11},
   'wind': {'speed': 3.36, 'deg': 180, 'gust': 4.42},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-09-22 06:00:00'},
  {'dt': 1758531600,
   'main': {'temp': 286.31,
    'feels_like': 285.51,
    'temp_min': 286.31,
    'temp_max': 286.31,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 70,
    'temp_kf': 0},

In [8]:
df_weather_data = pd.read_csv(r"data\cities_data.csv")
display(df_weather_data.head())

,id,city_name,latitude,longitude
0,29890d50-a6f7-41ad-bd8f-015ec8ecca5c,Mont Saint Michel,48.635954,-1.511460
1,dc15a9d5-d9e5-45cc-97a3-2485a4b5188c,Saint Malo,48.649518,-2.026041
2,88b85473-e091-486b-b6a3-02bc3286f9e6,Bayeux,49.276462,-0.702474
3,426d92ba-39e1-4221-9ccc-b780a8d4045a,Le Havre,49.493898,0.107973
4,0d09e03f-c058-49e2-be43-86ab6fb1af50,Rouen,49.440459,1.093966

In [9]:
def get_forecast_data(lat,lon):
    """
    This function takes a city latitude and a city longitude as input and returns a forecast data for 5 days.
    """
    exclude = "hourly,minutely"
    url_forecast_5days = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&exclude={exclude}&appid={API_KEY_WEATHER}&units=metric"
    
    try:
        response = requests.get(url_forecast_5days)
        response.raise_for_status()  # Raise an exception for non-200 status codes

        data = response.json()

        if len(data) == 0:
            print("City not found")
            return None # Return None to indicate unsuccessful retrieval
       
        return data
  
    except requests.exceptions.RequestException as e:
        print(f"Failed to retrieve data: {e}")
        return None # Return None to indicate unsuccessful retrieval

In [10]:
weather_data = df_weather_data.to_dict(orient='records')
display(weather_data)

[{'id': '29890d50-a6f7-41ad-bd8f-015ec8ecca5c',
  'city_name': 'Mont Saint Michel',
  'latitude': 48.6359541,
  'longitude': -1.51146},
 {'id': 'dc15a9d5-d9e5-45cc-97a3-2485a4b5188c',
  'city_name': 'Saint Malo',
  'latitude': 48.649518,
  'longitude': -2.0260409},
 {'id': '88b85473-e091-486b-b6a3-02bc3286f9e6',
  'city_name': 'Bayeux',
  'latitude': 49.2764624,
  'longitude': -0.7024738},
 {'id': '426d92ba-39e1-4221-9ccc-b780a8d4045a',
  'city_name': 'Le Havre',
  'latitude': 49.4938975,
  'longitude': 0.1079732},
 {'id': '0d09e03f-c058-49e2-be43-86ab6fb1af50',
  'city_name': 'Rouen',
  'latitude': 49.4404591,
  'longitude': 1.0939658},
 {'id': '7cef1672-a34e-41c0-a6d7-1260253307ee',
  'city_name': 'Paris',
  'latitude': 48.8588897,
  'longitude': 2.320041},
 {'id': 'b5006a04-d755-4cd5-bcee-57249e306037',
  'city_name': 'Amiens',
  'latitude': 49.8941708,
  'longitude': 2.2956951},
 {'id': 'db3f7e4d-1513-4473-b545-6662ea43c187',
  'city_name': 'Lille',
  'latitude': 50.6365654,
  'longitude': 3.0635282},
 {'id': '3e5a4baf-004d-4634-8445-b8bd565980ed',
  'city_name': 'Strasbourg',
  'latitude': 48.584614,
  'longitude': 7.7507127},
 {'id': '00e2db70-35f8-4080-a141-f88055759ae5',
  'city_name': 'Chateau du Haut Koenigsbourg',
  'latitude': 48.2494107,
  'longitude': 7.3443202},
 {'id': '91b25cc0-ba57-4367-85c3-7e507ec535cb',
  'city_name': 'Colmar',
  'latitude': 48.0777517,
  'longitude': 7.3579641},
 {'id': 'fbe64b26-b028-4bdc-869b-909973f5e9d2',
  'city_name': 'Eguisheim',
  'latitude': 48.0447968,
  'longitude': 7.3079618},
 {'id': '9c0e6ec4-5030-4ef5-bbdc-882d8aae2d0a',
  'city_name': 'Besancon',
  'latitude': 47.2380222,
  'longitude': 6.0243622},
 {'id': '1e1aed4d-70e1-48bc-a1a1-d7c698a6c0e5',
  'city_name': 'Dijon',
  'latitude': 47.3215806,
  'longitude': 5.0414701},
 {'id': 'd5991fe9-e421-44fc-9d46-95043bc4dc7c',
  'city_name': 'Annecy',
  'latitude': 45.8992348,
  'longitude': 6.1288847},
 {'id': '794e07dd-e1ef-44e0-aaa6-93b3dadaea60',
  'city_name': 'Grenoble',
  'latitude': 45.1875602,
  'longitude': 5.7357819},
 {'id': '9e02ebc6-5319-4653-96db-bbe63ee3e5a5',
  'city_name': 'Lyon',
  'latitude': 45.7578137,
  'longitude': 4.8320114},
 {'id': '2f7c77ce-7156-450c-bffc-ed4ad731edcb',
  'city_name': 'Gorges du Verdon',
  'latitude': 43.7496562,
  'longitude': 6.3285616},
 {'id': '87a31398-1e5b-47b8-a529-b79013bd384a',
  'city_name': 'Bormes les Mimosas',
  'latitude': 43.1506968,
  'longitude': 6.3419285},
 {'id': 'df334f74-b750-4c4a-90ff-b550bdf7915e',
  'city_name': 'Cassis',
  'latitude': 43.2140359,
  'longitude': 5.5396318},
 {'id': 'e38e17cf-5351-4dc6-9ec3-f6d43c063ae9',
  'city_name': 'Marseille',
  'latitude': 43.2961743,
  'longitude': 5.3699525},
 {'id': '25256697-856b-4178-bd3a-cd37a089139a',
  'city_name': 'Aix en Provence',
  'latitude': 43.5298424,
  'longitude': 5.4474738},
 {'id': 'c0ea9024-87a5-43ad-b895-2b6444607794',
  'city_name': 'Avignon',
  'latitude': 43.9492493,
  'longitude': 4.8059012},
 {'id': 'f7e01925-5dde-45ac-a11e-3fbb4ca6bcd7',
  'city_name': 'Uzes',
  'latitude': 44.0121279,
  'longitude': 4.4196718},
 {'id': '7e21bb9e-4fba-4a17-a50f-c05839b358be',
  'city_name': 'Nimes',
  'latitude': 43.8374249,
  'longitude': 4.3600687},
 {'id': 'e8bc4149-2b80-42ca-a23e-0bee491b74b0',
  'city_name': 'Aigues Mortes',
  'latitude': 43.5661521,
  'longitude': 4.19154},
 {'id': '2b05944e-c860-40de-b4a8-13639b53d2d2',
  'city_name': 'Saintes Maries de la mer',
  'latitude': 43.4515922,
  'longitude': 4.4277202},
 {'id': '6e56da4c-35af-402f-be11-389125c590d4',
  'city_name': 'Collioure',
  'latitude': 42.52505,
  'longitude': 3.0831554},
 {'id': '033e8575-f70f-4ca0-b827-153851002f8d',
  'city_name': 'Carcassonne',
  'latitude': 43.2130358,
  'longitude': 2.3491069},
 {'id': 'ce62a3a3-c13f-4bb7-9c0c-a2553b81cd84',
  'city_name': 'Ariege',
  'latitude': 42.9455368,
  'longitude': 1.4065544},
 {'id': '6554061f-306a-4b83-a1d4-3c802668b174',
  'city_name': 'Toulouse',
  'latitude': 43.6044622,
  'longitude': 1.4442469},
 {'id': '53ef551e-22e8-4f64-9c5e-082e8766ed25',
  'city_name': 'Montauban',
  'latitude': 44.0175835,
  'longitude': 1.3549991},
 {'id': '00321161-2ede-43bc-bdef-1346ba049a39',
  'city_name': 'Biarritz',
  'latitude': 43.4711437,
  'longitude': -1.5527266},
 {'id': 'a1066aad-8212-4a2e-b680-ca607724187b',
  'city_name': 'Bayonne',
  'latitude': 43.4945144,
  'longitude': -1.4736657},
 {'id': '79252ffd-b996-451d-9794-fe7ca05c1f90',
  'city_name': 'La Rochelle',
  'latitude': 46.159732,
  'longitude': -1.1515951}]

In [11]:
for city in weather_data:
    print(city)

{'id': '29890d50-a6f7-41ad-bd8f-015ec8ecca5c', 'city_name': 'Mont Saint Michel', 'latitude': 48.6359541, 'longitude': -1.51146}
{'id': 'dc15a9d5-d9e5-45cc-97a3-2485a4b5188c', 'city_name': 'Saint Malo', 'latitude': 48.649518, 'longitude': -2.0260409}
{'id': '88b85473-e091-486b-b6a3-02bc3286f9e6', 'city_name': 'Bayeux', 'latitude': 49.2764624, 'longitude': -0.7024738}
{'id': '426d92ba-39e1-4221-9ccc-b780a8d4045a', 'city_name': 'Le Havre', 'latitude': 49.4938975, 'longitude': 0.1079732}
{'id': '0d09e03f-c058-49e2-be43-86ab6fb1af50', 'city_name': 'Rouen', 'latitude': 49.4404591, 'longitude': 1.0939658}
{'id': '7cef1672-a34e-41c0-a6d7-1260253307ee', 'city_name': 'Paris', 'latitude': 48.8588897, 'longitude': 2.320041}
{'id': 'b5006a04-d755-4cd5-bcee-57249e306037', 'city_name': 'Amiens', 'latitude': 49.8941708, 'longitude': 2.2956951}
{'id': 'db3f7e4d-1513-4473-b545-6662ea43c187', 'city_name': 'Lille', 'latitude': 50.6365654, 'longitude': 3.0635282}
{'id': '3e5a4baf-004d-4634-8445-b8bd565980ed', 'city_name': 'Strasbourg', 'latitude': 48.584614, 'longitude': 7.7507127}
{'id': '00e2db70-35f8-4080-a141-f88055759ae5', 'city_name': 'Chateau du Haut Koenigsbourg', 'latitude': 48.2494107, 'longitude': 7.3443202}
{'id': '91b25cc0-ba57-4367-85c3-7e507ec535cb', 'city_name': 'Colmar', 'latitude': 48.0777517, 'longitude': 7.3579641}
{'id': 'fbe64b26-b028-4bdc-869b-909973f5e9d2', 'city_name': 'Eguisheim', 'latitude': 48.0447968, 'longitude': 7.3079618}
{'id': '9c0e6ec4-5030-4ef5-bbdc-882d8aae2d0a', 'city_name': 'Besancon', 'latitude': 47.2380222, 'longitude': 6.0243622}
{'id': '1e1aed4d-70e1-48bc-a1a1-d7c698a6c0e5', 'city_name': 'Dijon', 'latitude': 47.3215806, 'longitude': 5.0414701}
{'id': 'd5991fe9-e421-44fc-9d46-95043bc4dc7c', 'city_name': 'Annecy', 'latitude': 45.8992348, 'longitude': 6.1288847}
{'id': '794e07dd-e1ef-44e0-aaa6-93b3dadaea60', 'city_name': 'Grenoble', 'latitude': 45.1875602, 'longitude': 5.7357819}
{'id': '9e02ebc6-5319-4653-96db-bbe63ee3e5a5', 'city_name': 'Lyon', 'latitude': 45.7578137, 'longitude': 4.8320114}
{'id': '2f7c77ce-7156-450c-bffc-ed4ad731edcb', 'city_name': 'Gorges du Verdon', 'latitude': 43.7496562, 'longitude': 6.3285616}
{'id': '87a31398-1e5b-47b8-a529-b79013bd384a', 'city_name': 'Bormes les Mimosas', 'latitude': 43.1506968, 'longitude': 6.3419285}
{'id': 'df334f74-b750-4c4a-90ff-b550bdf7915e', 'city_name': 'Cassis', 'latitude': 43.2140359, 'longitude': 5.5396318}
{'id': 'e38e17cf-5351-4dc6-9ec3-f6d43c063ae9', 'city_name': 'Marseille', 'latitude': 43.2961743, 'longitude': 5.3699525}
{'id': '25256697-856b-4178-bd3a-cd37a089139a', 'city_name': 'Aix en Provence', 'latitude': 43.5298424, 'longitude': 5.4474738}
{'id': 'c0ea9024-87a5-43ad-b895-2b6444607794', 'city_name': 'Avignon', 'latitude': 43.9492493, 'longitude': 4.8059012}
{'id': 'f7e01925-5dde-45ac-a11e-3fbb4ca6bcd7', 'city_name': 'Uzes', 'latitude': 44.0121279, 'longitude': 4.4196718}
{'id': '7e21bb9e-4fba-4a17-a50f-c05839b358be', 'city_name': 'Nimes', 'latitude': 43.8374249, 'longitude': 4.3600687}
{'id': 'e8bc4149-2b80-42ca-a23e-0bee491b74b0', 'city_name': 'Aigues Mortes', 'latitude': 43.5661521, 'longitude': 4.19154}
{'id': '2b05944e-c860-40de-b4a8-13639b53d2d2', 'city_name': 'Saintes Maries de la mer', 'latitude': 43.4515922, 'longitude': 4.4277202}
{'id': '6e56da4c-35af-402f-be11-389125c590d4', 'city_name': 'Collioure', 'latitude': 42.52505, 'longitude': 3.0831554}
{'id': '033e8575-f70f-4ca0-b827-153851002f8d', 'city_name': 'Carcassonne', 'latitude': 43.2130358, 'longitude': 2.3491069}
{'id': 'ce62a3a3-c13f-4bb7-9c0c-a2553b81cd84', 'city_name': 'Ariege', 'latitude': 42.9455368, 'longitude': 1.4065544}
{'id': '6554061f-306a-4b83-a1d4-3c802668b174', 'city_name': 'Toulouse', 'latitude': 43.6044622, 'longitude': 1.4442469}
{'id': '53ef551e-22e8-4f64-9c5e-082e8766ed25', 'city_name': 'Montauban', 'latitude': 44.0175835, 'longitude': 1.3549991}
{'id': '00321161-2ede-43bc-bdef-1346ba049a39', 'city_name': 'Biarritz', 'latitude': 43.4711437, 'longitude': -1.5527266}
{'id': 'a1066aad-8212-4a2e-b680-ca607724187b', 'city_name': 'Bayonne', 'latitude': 43.4945144, 'longitude': -1.4736657}
{'id': '79252ffd-b996-451d-9794-fe7ca05c1f90', 'city_name': 'La Rochelle', 'latitude': 46.159732, 'longitude': -1.1515951}

In [12]:
# get the weather data for each city in the list
city_weather_data = []
for city in weather_data:
    city_name = city['city_name']
    lat = city['latitude']
    lon = city['longitude']
    city_weather = get_forecast_data(lat, lon)
    #print(city_weather)
    current_city = {"city": city_name , "weather_info" : city_weather}
    city_weather_data.append(current_city)
    time.sleep(0.2)

display(city_weather_data)

[{'city': 'Mont Saint Michel',
  'weather_info': {'cod': '200',
   'message': 0,
   'cnt': 40,
   'list': [{'dt': 1757516400,
     'main': {'temp': 17.13,
      'feels_like': 17.2,
      'temp_min': 17.13,
      'temp_max': 17.4,
      'pressure': 1004,
      'sea_level': 1004,
      'grnd_level': 998,
      'humidity': 88,
      'temp_kf': -0.27},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 100},
     'wind': {'speed': 7.07, 'deg': 214, 'gust': 11.05},
     'visibility': 10000,
     'pop': 1,
     'rain': {'3h': 0.98},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-10 15:00:00'},
    {'dt': 1757527200,
     'main': {'temp': 16.54,
      'feels_like': 16.47,
      'temp_min': 16.32,
      'temp_max': 16.54,
      'pressure': 1004,
      'sea_level': 1004,
      'grnd_level': 999,
      'humidity': 85,
      'temp_kf': 0.22},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 92},
     'wind': {'speed': 6.37, 'deg': 279, 'gust': 10.51},
     'visibility': 10000,
     'pop': 1,
     'rain': {'3h': 0.8},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-10 18:00:00'},
    {'dt': 1757538000,
     'main': {'temp': 15.39,
      'feels_like': 15.23,
      'temp_min': 15.39,
      'temp_max': 15.39,
      'pressure': 1008,
      'sea_level': 1008,
      'grnd_level': 1003,
      'humidity': 86,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10n'}],
     'clouds': {'all': 20},
     'wind': {'speed': 7.33, 'deg': 275, 'gust': 12.02},
     'visibility': 10000,
     'pop': 0.3,
     'rain': {'3h': 0.28},
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-10 21:00:00'},
    {'dt': 1757548800,
     'main': {'temp': 13.75,
      'feels_like': 13.56,
      'temp_min': 13.75,
      'temp_max': 13.75,
      'pressure': 1010,
      'sea_level': 1010,
      'grnd_level': 1004,
      'humidity': 91,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10n'}],
     'clouds': {'all': 21},
     'wind': {'speed': 6.32, 'deg': 245, 'gust': 10.54},
     'visibility': 10000,
     'pop': 0.38,
     'rain': {'3h': 0.2},
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-11 00:00:00'},
    {'dt': 1757559600,
     'main': {'temp': 12.87,
      'feels_like': 12.64,
      'temp_min': 12.87,
      'temp_max': 12.87,
      'pressure': 1010,
      'sea_level': 1010,
      'grnd_level': 1005,
      'humidity': 93,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10n'}],
     'clouds': {'all': 26},
     'wind': {'speed': 5.36, 'deg': 231, 'gust': 10.42},
     'visibility': 10000,
     'pop': 0.32,
     'rain': {'3h': 0.21},
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-11 03:00:00'},
    {'dt': 1757570400,
     'main': {'temp': 13.51,
      'feels_like': 13.29,
      'temp_min': 13.51,
      'temp_max': 13.51,
      'pressure': 1010,
      'sea_level': 1010,
      'grnd_level': 1005,
      'humidity': 91,
      'temp_kf': 0},
     'weather': [{'id': 802,
       'main': 'Clouds',
       'description': 'scattered clouds',
       'icon': '03d'}],
     'clouds': {'all': 36},
     'wind': {'speed': 5.87, 'deg': 213, 'gust': 12.14},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-11 06:00:00'},
    {'dt': 1757581200,
     'main': {'temp': 16.26,
      'feels_like': 16,
      'temp_min': 16.26,
      'temp_max': 16.26,
      'pressure': 1011,
      'sea_level': 1011,
      'grnd_level': 1006,
      'humidity': 79,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 86},
     'wind': {'speed': 7.9, 'deg': 232, 'gust': 12.17},
     'visibility': 10000,
     'pop': 0.9,
     'rain': {'3h': 0.58},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-11 09:00:00'},
    {'dt': 1757592000,
     'main': {'temp': 17.29,
      'feels_like': 17.01,
      'temp_min': 17.29,
      'temp_max': 17.29,
      'pressure': 1011,
      'sea_level': 1011,
      'grnd_level': 1006,
      'humidity': 74,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 79},
     'wind': {'speed': 8.27, 'deg': 271, 'gust': 10.91},
     'visibility': 10000,
     'pop': 1,
     'rain': {'3h': 1.43},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-11 12:00:00'},
    {'dt': 1757602800,
     'main': {'temp': 17.33,
      'feels_like': 16.79,
      'temp_min': 17.33,
      'temp_max': 17.33,
      'pressure': 1011,
      'sea_level': 1011,
      'grnd_level': 1006,
      'humidity': 64,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 69},
     'wind': {'speed': 6.11, 'deg': 304, 'gust': 8.09},
     'visibility': 10000,
     'pop': 0.99,
     'rain': {'3h': 0.58},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-11 15:00:00'},
    {'dt': 1757613600,
     'main': {'temp': 15.07,
      'feels_like': 14.56,
      'temp_min': 15.07,
      'temp_max': 15.07,
      'pressure': 1013,
      'sea_level': 1013,
      'grnd_level': 1008,
      'humidity': 74,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 69},
     'wind': {'speed': 6.25, 'deg': 277, 'gust': 10.21},
     'visibility': 10000,
     'pop': 1,
     'rain': {'3h': 1.51},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-11 18:00:00'},
    {'dt': 1757624400,
     'main': {'temp': 12.67,
      'feels_like': 12.13,
      'temp_min': 12.67,
      'temp_max': 12.67,
      'pressure': 1014,
      'sea_level': 1014,
      'grnd_level': 1009,
      'humidity': 82,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10n'}],
     'clouds': {'all': 25},
     'wind': {'speed': 6.25, 'deg': 240, 'gust': 11.32},
     'visibility': 10000,
     'pop': 0.62,
     'rain': {'3h': 0.34},
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-11 21:00:00'},
    {'dt': 1757635200,
     'main': {'temp': 11.94,
      'feels_like': 11.49,
      'temp_min': 11.94,
      'temp_max': 11.94,
      'pressure': 1015,
      'sea_level': 1015,
      'grnd_level': 1010,
      'humidity': 88,
      'temp_kf': 0},
     'weather': [{'id': 801,
       'main': 'Clouds',
       'description': 'few clouds',
       'icon': '02n'}],
     'clouds': {'all': 24},
     'wind': {'speed': 6.13, 'deg': 233, 'gust': 11.49},
     'visibility': 10000,
     'pop': 0.14,
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-12 00:00:00'},
    {'dt': 1757646000,
     'main': {'temp': 11.18,
      'feels_like': 10.73,
      'temp_min': 11.18,
      'temp_max': 11.18,
      'pressure': 1015,
      'sea_level': 1015,
      'grnd_level': 1010,
      'humidity': 91,
      'temp_kf': 0},
     'weather': [{'id': 801,
       'main': 'Clouds',
       'description': 'few clouds',
       'icon': '02n'}],
     'clouds': {'all': 11},
     'wind': {'speed': 5.36, 'deg': 233, 'gust': 10.33},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-12 03:00:00'},
    {'dt': 1757656800,
     'main': {'temp': 10.88,
      'feels_like': 10.4,
      'temp_min': 10.88,
      'temp_max': 10.88,
      'pressure': 1016,
      'sea_level': 1016,
      'grnd_level': 1011,
      'humidity': 91,
      'temp_kf': 0},
     'weather': [{'id': 800,
       'main': 'Clear',
       'description': 'clear sky',
       'icon': '01d'}],
     'clouds': {'all': 9},
     'wind': {'speed': 5.02, 'deg': 223, 'gust': 10.12},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-12 06:00:00'},
    {'dt': 1757667600,
     'main': {'temp': 16.09,
      'feels_like': 15.5,
      'temp_min': 16.09,
      'temp_max': 16.09,
      'pressure': 1017,
      'sea_level': 1017,
      'grnd_level': 1012,
      'humidity': 67,
      'temp_kf': 0},
     'weather': [{'id': 801,
       'main': 'Clouds',
       'description': 'few clouds',
       'icon': '02d'}],
     'clouds': {'all': 13},
     'wind': {'speed': 6.01, 'deg': 243, 'gust': 8.04},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-12 09:00:00'},
    {'dt': 1757678400,
     'main': {'temp': 19.9,
      'feels_like': 19.15,
      'temp_min': 19.9,
      'temp_max': 19.9,
      'pressure': 1017,
      'sea_level': 1017,
      'grnd_level': 1012,
      'humidity': 46,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 10},
     'wind': {'speed': 5.91, 'deg': 257, 'gust': 9.08},
     'visibility': 10000,
     'pop': 0.2,
     'rain': {'3h': 0.13},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-12 12:00:00'},
    {'dt': 1757689200,
     'main': {'temp': 18.31,
      'feels_like': 17.61,
      'temp_min': 18.31,
      'temp_max': 18.31,
      'pressure': 1016,
      'sea_level': 1016,
      'grnd_level': 1011,
      'humidity': 54,
      'temp_kf': 0},
     'weather': [{'id': 804,
       'main': 'Clouds',
       'description': 'overcast clouds',
       'icon': '04d'}],
     'clouds': {'all': 87},
     'wind': {'speed': 3.17, 'deg': 268, 'gust': 6.05},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-12 15:00:00'},
    {'dt': 1757700000,
     'main': {'temp': 17.57,
      'feels_like': 16.9,
      'temp_min': 17.57,
      'temp_max': 17.57,
      'pressure': 1016,
      'sea_level': 1016,
      'grnd_level': 1010,
      'humidity': 58,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 93},
     'wind': {'speed': 6.46, 'deg': 222, 'gust': 9.96},
     'visibility': 10000,
     'pop': 0.21,
     'rain': {'3h': 0.22},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-12 18:00:00'},
    {'dt': 1757710800,
     'main': {'temp': 14.68,
      'feels_like': 14.29,
      'temp_min': 14.68,
      'temp_max': 14.68,
      'pressure': 1015,
      'sea_level': 1015,
      'grnd_level': 1010,
      'humidity': 80,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10n'}],
     'clouds': {'all': 100},
     'wind': {'speed': 5.45, 'deg': 209, 'gust': 9.53},
     'visibility': 10000,
     'pop': 0.59,
     'rain': {'3h': 0.29},
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-12 21:00:00'},
    {'dt': 1757721600,
     'main': {'temp': 13.78,
      'feels_like': 13.59,
      'temp_min': 13.78,
      'temp_max': 13.78,
      'pressure': 1014,
      'sea_level': 1014,
      'grnd_level': 1009,
      'humidity': 91,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10n'}],
     'clouds': {'all': 100},
     'wind': {'speed': 7.59, 'deg': 196, 'gust': 13.61},
     'visibility': 10000,
     'pop': 1,
     'rain': {'3h': 2.36},
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-13 00:00:00'},
    {'dt': 1757732400,
     'main': {'temp': 13.76,
      'feels_like': 13.49,
      'temp_min': 13.76,
      'temp_max': 13.76,
      'pressure': 1014,
      'sea_level': 1014,
      'grnd_level': 1009,
      'humidity': 88,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10n'}],
     'clouds': {'all': 100},
     'wind': {'speed': 5.73, 'deg': 238, 'gust': 10.34},
     'visibility': 10000,
     'pop': 1,
     'rain': {'3h': 1.25},
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-13 03:00:00'},
    {'dt': 1757743200,
     'main': {'temp': 13.36,
      'feels_like': 13.15,
      'temp_min': 13.36,
      'temp_max': 13.36,
      'pressure': 1014,
      'sea_level': 1014,
      'grnd_level': 1009,
      'humidity': 92,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 94},
     'wind': {'speed': 5.77, 'deg': 213, 'gust': 10.46},
     'visibility': 10000,
     'pop': 1,
     'rain': {'3h': 0.12},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-13 06:00:00'},
    {'dt': 1757754000,
     'main': {'temp': 16.23,
      'feels_like': 15.95,
      'temp_min': 16.23,
      'temp_max': 16.23,
      'pressure': 1015,
      'sea_level': 1015,
      'grnd_level': 1010,
      'humidity': 78,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 28},
     'wind': {'speed': 6.52, 'deg': 258, 'gust': 8.74},
     'visibility': 10000,
     'pop': 0.33,
     'rain': {'3h': 0.23},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-13 09:00:00'},
    {'dt': 1757764800,
     'main': {'temp': 18.65,
      'feels_like': 17.98,
      'temp_min': 18.65,
      'temp_max': 18.65,
      'pressure': 1016,
      'sea_level': 1016,
      'grnd_level': 1011,
      'humidity': 54,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 42},
     'wind': {'speed': 5.79, 'deg': 281, 'gust': 8.83},
     'visibility': 10000,
     'pop': 0.31,
     'rain': {'3h': 0.11},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-13 12:00:00'},
    {'dt': 1757775600,
     'main': {'temp': 18.42,
      'feels_like': 17.78,
      'temp_min': 18.42,
      'temp_max': 18.42,
      'pressure': 1017,
      'sea_level': 1017,
      'grnd_level': 1012,
      'humidity': 56,
      'temp_kf': 0},
     'weather': [{'id': 801,
       'main': 'Clouds',
       'description': 'few clouds',
       'icon': '02d'}],
     'clouds': {'all': 16},
     'wind': {'speed': 6.64, 'deg': 314, 'gust': 7.54},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-13 15:00:00'},
    {'dt': 1757786400,
     'main': {'temp': 15.48,
      'feels_like': 14.91,
      'temp_min': 15.48,
      'temp_max': 15.48,
      'pressure': 1019,
      'sea_level': 1019,
      'grnd_level': 1013,
      'humidity': 70,
      'temp_kf': 0},
     'weather': [{'id': 801,
       'main': 'Clouds',
       'description': 'few clouds',
       'icon': '02d'}],
     'clouds': {'all': 16},
     'wind': {'speed': 4.36, 'deg': 315, 'gust': 7.76},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-13 18:00:00'},
    {'dt': 1757797200,
     'main': {'temp': 13.46,
      'feels_like': 12.9,
      'temp_min': 13.46,
      'temp_max': 13.46,
      'pressure': 1020,
      'sea_level': 1020,
      'grnd_level': 1015,
      'humidity': 78,
      'temp_kf': 0},
     'weather': [{'id': 804,
       'main': 'Clouds',
       'description': 'overcast clouds',
       'icon': '04n'}],
     'clouds': {'all': 100},
     'wind': {'speed': 3.41, 'deg': 215, 'gust': 5.06},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-13 21:00:00'},
    {'dt': 1757808000,
     'main': {'temp': 11.56,
      'feels_like': 10.91,
      'temp_min': 11.56,
      'temp_max': 11.56,
      'pressure': 1020,
      'sea_level': 1020,
      'grnd_level': 1015,
      'humidity': 82,
      'temp_kf': 0},
     'weather': [{'id': 804,
       'main': 'Clouds',
       'description': 'overcast clouds',
       'icon': '04n'}],
     'clouds': {'all': 100},
     'wind': {'speed': 3.8, 'deg': 195, 'gust': 5.61},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-14 00:00:00'},
    {'dt': 1757818800,
     'main': {'temp': 11.9,
      'feels_like': 11.39,
      'temp_min': 11.9,
      'temp_max': 11.9,
      'pressure': 1018,
      'sea_level': 1018,
      'grnd_level': 1013,
      'humidity': 86,
      'temp_kf': 0},
     'weather': [{'id': 804,
       'main': 'Clouds',
       'description': 'overcast clouds',
       'icon': '04n'}],
     'clouds': {'all': 100},
     'wind': {'speed': 4.96, 'deg': 172, 'gust': 11.31},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'n'},
     'dt_txt': '2025-09-14 03:00:00'},
    {'dt': 1757829600,
     'main': {'temp': 14.54,
      'feels_like': 14.48,
      'temp_min': 14.54,
      'temp_max': 14.54,
      'pressure': 1016,
      'sea_level': 1016,
      'grnd_level': 1010,
      'humidity': 93,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 100},
     'wind': {'speed': 8.03, 'deg': 177, 'gust': 14.82},
     'visibility': 6490,
     'pop': 0.98,
     'rain': {'3h': 0.89},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-14 06:00:00'},
    {'dt': 1757840400,
     'main': {'temp': 17.15,
      'feels_like': 17.27,
      'temp_min': 17.15,
      'temp_max': 17.15,
      'pressure': 1014,
      'sea_level': 1014,
      'grnd_level': 1009,
      'humidity': 90,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 100},
     'wind': {'speed': 10.2, 'deg': 199, 'gust': 16.86},
     'visibility': 10000,
     'pop': 0.99,
     'rain': {'3h': 1.2},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-14 09:00:00'},
    {'dt': 1757851200,
     'main': {'temp': 21.18,
      'feels_like': 21.29,
      'temp_min': 21.18,
      'temp_max': 21.18,
      'pressure': 1012,
      'sea_level': 1012,
      'grnd_level': 1007,
      'humidity': 74,
      'temp_kf': 0},
     'weather': [{'id': 804,
       'main': 'Clouds',
       'description': 'overcast clouds',
       'icon': '04d'}],
     'clouds': {'all': 100},
     'wind': {'speed': 11.19, 'deg': 208, 'gust': 16.22},
     'visibility': 10000,
     'pop': 0.9,
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-14 12:00:00'},
    {'dt': 1757862000,
     'main': {'temp': 22.66,
      'feels_like': 22.57,
      'temp_min': 22.66,
      'temp_max': 22.66,
      'pressure': 1011,
      'sea_level': 1011,
      'grnd_level': 1006,
      'humidity': 61,
      'temp_kf': 0},
     'weather': [{'id': 804,
       'main': 'Clouds',
       'description': 'overcast clouds',
       'icon': '04d'}],
     'clouds': {'all': 92},
     'wind': {'speed': 11.76, 'deg': 216, 'gust': 17.63},
     'visibility': 10000,
     'pop': 0,
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-14 15:00:00'},
    {'dt': 1757872800,
     'main': {'temp': 18.49,
      'feels_like': 18.77,
      'temp_min': 18.49,
      'temp_max': 18.49,
      'pressure': 1012,
      'sea_level': 1012,
      'grnd_level': 1007,
      'humidity': 91,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10d'}],
     'clouds': {'all': 96},
     'wind': {'speed': 10.35, 'deg': 244, 'gust': 16.26},
     'visibility': 10000,
     'pop': 1,
     'rain': {'3h': 1.79},
     'sys': {'pod': 'd'},
     'dt_txt': '2025-09-14 18:00:00'},
    {'dt': 1757883600,
     'main': {'temp': 13.96,
      'feels_like': 13.66,
      'temp_min': 13.96,
      'temp_max': 13.96,
      'pressure': 1015,
      'sea_level': 1015,
      'grnd_level': 1009,
      'humidity': 86,
      'temp_kf': 0},
     'weather': [{'id': 500,
       'main': 'Rain',
       'description': 'light rain',
       'icon': '10n'}],
     'clouds': {'all': 25},
     'wind': {'speed': 7.34, 'deg': 237, 'gust': 12.96},
     'visibility': 10000,
     'pop': 0.36,
     'rain': {'3h': 0.18},
     'sys': {'pod': 'n'},

In [13]:
forecast_filtered = []
for city in city_weather_data:
    city_name  = city["city"]
    #print(city_name)
    weather_info = city["weather_info"]
    weather_info_data = weather_info["list"]
    for info in weather_info_data:
        day = info["dt_txt"].split(" ")[0]
        #print(day)
        temp = info["main"]["temp"]
        #print(temp)
        weather = info["weather"][0]["description"]
        #print(weather)
        wind_speed = info["wind"]["speed"]
        #print(wind_speed)
        humidity = info["main"]["humidity"]
        #print(humidity)
        row = {"city_name":city_name, "day": day, "temp": temp, "weather": weather, "wind_speed": wind_speed, "humidity": humidity}
        forecast_filtered.append(row)

display(forecast_filtered)

[{'city_name': 'Mont Saint Michel',
  'day': '2025-09-10',
  'temp': 17.13,
  'weather': 'light rain',
  'wind_speed': 7.07,
  'humidity': 88},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-10',
  'temp': 16.54,
  'weather': 'light rain',
  'wind_speed': 6.37,
  'humidity': 85},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-10',
  'temp': 15.39,
  'weather': 'light rain',
  'wind_speed': 7.33,
  'humidity': 86},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-11',
  'temp': 13.75,
  'weather': 'light rain',
  'wind_speed': 6.32,
  'humidity': 91},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-11',
  'temp': 12.87,
  'weather': 'light rain',
  'wind_speed': 5.36,
  'humidity': 93},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-11',
  'temp': 13.51,
  'weather': 'scattered clouds',
  'wind_speed': 5.87,
  'humidity': 91},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-11',
  'temp': 16.26,
  'weather': 'light rain',
  'wind_speed': 7.9,
  'humidity': 79},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-11',
  'temp': 17.29,
  'weather': 'light rain',
  'wind_speed': 8.27,
  'humidity': 74},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-11',
  'temp': 17.33,
  'weather': 'light rain',
  'wind_speed': 6.11,
  'humidity': 64},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-11',
  'temp': 15.07,
  'weather': 'light rain',
  'wind_speed': 6.25,
  'humidity': 74},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-11',
  'temp': 12.67,
  'weather': 'light rain',
  'wind_speed': 6.25,
  'humidity': 82},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-12',
  'temp': 11.94,
  'weather': 'few clouds',
  'wind_speed': 6.13,
  'humidity': 88},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-12',
  'temp': 11.18,
  'weather': 'few clouds',
  'wind_speed': 5.36,
  'humidity': 91},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-12',
  'temp': 10.88,
  'weather': 'clear sky',
  'wind_speed': 5.02,
  'humidity': 91},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-12',
  'temp': 16.09,
  'weather': 'few clouds',
  'wind_speed': 6.01,
  'humidity': 67},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-12',
  'temp': 19.9,
  'weather': 'light rain',
  'wind_speed': 5.91,
  'humidity': 46},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-12',
  'temp': 18.31,
  'weather': 'overcast clouds',
  'wind_speed': 3.17,
  'humidity': 54},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-12',
  'temp': 17.57,
  'weather': 'light rain',
  'wind_speed': 6.46,
  'humidity': 58},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-12',
  'temp': 14.68,
  'weather': 'light rain',
  'wind_speed': 5.45,
  'humidity': 80},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-13',
  'temp': 13.78,
  'weather': 'light rain',
  'wind_speed': 7.59,
  'humidity': 91},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-13',
  'temp': 13.76,
  'weather': 'light rain',
  'wind_speed': 5.73,
  'humidity': 88},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-13',
  'temp': 13.36,
  'weather': 'light rain',
  'wind_speed': 5.77,
  'humidity': 92},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-13',
  'temp': 16.23,
  'weather': 'light rain',
  'wind_speed': 6.52,
  'humidity': 78},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-13',
  'temp': 18.65,
  'weather': 'light rain',
  'wind_speed': 5.79,
  'humidity': 54},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-13',
  'temp': 18.42,
  'weather': 'few clouds',
  'wind_speed': 6.64,
  'humidity': 56},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-13',
  'temp': 15.48,
  'weather': 'few clouds',
  'wind_speed': 4.36,
  'humidity': 70},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-13',
  'temp': 13.46,
  'weather': 'overcast clouds',
  'wind_speed': 3.41,
  'humidity': 78},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-14',
  'temp': 11.56,
  'weather': 'overcast clouds',
  'wind_speed': 3.8,
  'humidity': 82},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-14',
  'temp': 11.9,
  'weather': 'overcast clouds',
  'wind_speed': 4.96,
  'humidity': 86},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-14',
  'temp': 14.54,
  'weather': 'light rain',
  'wind_speed': 8.03,
  'humidity': 93},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-14',
  'temp': 17.15,
  'weather': 'light rain',
  'wind_speed': 10.2,
  'humidity': 90},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-14',
  'temp': 21.18,
  'weather': 'overcast clouds',
  'wind_speed': 11.19,
  'humidity': 74},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-14',
  'temp': 22.66,
  'weather': 'overcast clouds',
  'wind_speed': 11.76,
  'humidity': 61},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-14',
  'temp': 18.49,
  'weather': 'light rain',
  'wind_speed': 10.35,
  'humidity': 91},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-14',
  'temp': 13.96,
  'weather': 'light rain',
  'wind_speed': 7.34,
  'humidity': 86},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-15',
  'temp': 13.1,
  'weather': 'few clouds',
  'wind_speed': 7.27,
  'humidity': 90},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-15',
  'temp': 13.17,
  'weather': 'broken clouds',
  'wind_speed': 7.72,
  'humidity': 89},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-15',
  'temp': 12.63,
  'weather': 'light rain',
  'wind_speed': 7.47,
  'humidity': 88},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-15',
  'temp': 16.55,
  'weather': 'light rain',
  'wind_speed': 8.69,
  'humidity': 64},
 {'city_name': 'Mont Saint Michel',
  'day': '2025-09-15',
  'temp': 18.91,
  'weather': 'light rain',
  'wind_speed': 9.35,
  'humidity': 54},
 {'city_name': 'Saint Malo',
  'day': '2025-09-10',
  'temp': 17.5,
  'weather': 'light rain',
  'wind_speed': 9.81,
  'humidity': 90},
 {'city_name': 'Saint Malo',
  'day': '2025-09-10',
  'temp': 16.74,
  'weather': 'light rain',
  'wind_speed': 9.87,
  'humidity': 85},
 {'city_name': 'Saint Malo',
  'day': '2025-09-10',
  'temp': 15.94,
  'weather': 'light rain',
  'wind_speed': 9.37,
  'humidity': 80},
 {'city_name': 'Saint Malo',
  'day': '2025-09-11',
  'temp': 14.45,
  'weather': 'light rain',
  'wind_speed': 7.66,
  'humidity': 88},
 {'city_name': 'Saint Malo',
  'day': '2025-09-11',
  'temp': 13.83,
  'weather': 'light rain',
  'wind_speed': 6.97,
  'humidity': 88},
 {'city_name': 'Saint Malo',
  'day': '2025-09-11',
  'temp': 14.68,
  'weather': 'scattered clouds',
  'wind_speed': 8.06,
  'humidity': 82},
 {'city_name': 'Saint Malo',
  'day': '2025-09-11',
  'temp': 17.03,
  'weather': 'light rain',
  'wind_speed': 9.11,
  'humidity': 68},
 {'city_name': 'Saint Malo',
  'day': '2025-09-11',
  'temp': 18.17,
  'weather': 'light rain',
  'wind_speed': 8.46,
  'humidity': 62},
 {'city_name': 'Saint Malo',
  'day': '2025-09-11',
  'temp': 17.82,
  'weather': 'light rain',
  'wind_speed': 8.98,
  'humidity': 61},
 {'city_name': 'Saint Malo',
  'day': '2025-09-11',
  'temp': 16.04,
  'weather': 'light rain',
  'wind_speed': 8.8,
  'humidity': 68},
 {'city_name': 'Saint Malo',
  'day': '2025-09-11',
  'temp': 13.79,
  'weather': 'light rain',
  'wind_speed': 7.5,
  'humidity': 78},
 {'city_name': 'Saint Malo',
  'day': '2025-09-12',
  'temp': 13.08,
  'weather': 'few clouds',
  'wind_speed': 7.8,
  'humidity': 84},
 {'city_name': 'Saint Malo',
  'day': '2025-09-12',
  'temp': 12.36,
  'weather': 'clear sky',
  'wind_speed': 6.78,
  'humidity': 86},
 {'city_name': 'Saint Malo',
  'day': '2025-09-12',
  'temp': 12.17,
  'weather': 'clear sky',
  'wind_speed': 7.04,
  'humidity': 87},
 {'city_name': 'Saint Malo',
  'day': '2025-09-12',
  'temp': 16.53,
  'weather': 'clear sky',
  'wind_speed': 7.51,
  'humidity': 63},
 {'city_name': 'Saint Malo',
  'day': '2025-09-12',
  'temp': 19.54,
  'weather': 'clear sky',
  'wind_speed': 6.71,
  'humidity': 48},
 {'city_name': 'Saint Malo',
  'day': '2025-09-12',
  'temp': 19.52,
  'weather': 'broken clouds',
  'wind_speed': 5.85,
  'humidity': 51},
 {'city_name': 'Saint Malo',
  'day': '2025-09-12',
  'temp': 17.89,
  'weather': 'light rain',
  'wind_speed': 7.95,
  'humidity': 60},
 {'city_name': 'Saint Malo',
  'day': '2025-09-12',
  'temp': 14.98,
  'weather': 'light rain',
  'wind_speed': 6.97,
  'humidity': 77},
 {'city_name': 'Saint Malo',
  'day': '2025-09-13',
  'temp': 14.31,
  'weather': 'light rain',
  'wind_speed': 8.3,
  'humidity': 87},
 {'city_name': 'Saint Malo',
  'day': '2025-09-13',
  'temp': 14.23,
  'weather': 'light rain',
  'wind_speed': 7.29,
  'humidity': 83},
 {'city_name': 'Saint Malo',
  'day': '2025-09-13',
  'temp': 13.51,
  'weather': 'overcast clouds',
  'wind_speed': 6.91,
  'humidity': 91},
 {'city_name': 'Saint Malo',
  'day': '2025-09-13',
  'temp': 16.55,
  'weather': 'light rain',
  'wind_speed': 7.13,
  'humidity': 69},
 {'city_name': 'Saint Malo',
  'day': '2025-09-13',
  'temp': 18.76,
  'weather': 'few clouds',
  'wind_speed': 6.95,
  'humidity': 53},
 {'city_name': 'Saint Malo',
  'day': '2025-09-13',
  'temp': 18.42,
  'weather': 'broken clouds',
  'wind_speed': 7.71,
  'humidity': 55},
 {'city_name': 'Saint Malo',
  'day': '2025-09-13',
  'temp': 16.93,
  'weather': 'broken clouds',
  'wind_speed': 6.35,
  'humidity': 61},
 {'city_name': 'Saint Malo',
  'day': '2025-09-13',
  'temp': 14.46,
  'weather': 'overcast clouds',
  'wind_speed': 5.76,
  'humidity': 71},
 {'city_name': 'Saint Malo',
  'day': '2025-09-14',
  'temp': 13.44,
  'weather': 'overcast clouds',
  'wind_speed': 5.58,
  'humidity': 77},
 {'city_name': 'Saint Malo',
  'day': '2025-09-14',
  'temp': 14.15,
  'weather': 'overcast clouds',
  'wind_speed': 7.17,
  'humidity': 84},
 {'city_name': 'Saint Malo',
  'day': '2025-09-14',
  'temp': 15.91,
  'weather': 'light rain',
  'wind_speed': 9.68,
  'humidity': 90},
 {'city_name': 'Saint Malo',
  'day': '2025-09-14',
  'temp': 18.07,
  'weather': 'light rain',
  'wind_speed': 11.54,
  'humidity': 89},
 {'city_name': 'Saint Malo',
  'day': '2025-09-14',
  'temp': 22.2,
  'weather': 'overcast clouds',
  'wind_speed': 13.82,
  'humidity': 66},
 {'city_name': 'Saint Malo',
  'day': '2025-09-14',
  'temp': 21.99,
  'weather': 'overcast clouds',
  'wind_speed': 12.95,
  'humidity': 64},
 {'city_name': 'Saint Malo',
  'day': '2025-09-14',
  'temp': 18.2,
  'weather': 'light rain',
  'wind_speed': 11.02,
  'humidity': 78},
 {'city_name': 'Saint Malo',
  'day': '2025-09-14',
  'temp': 15.06,
  'weather': 'clear sky',
  'wind_speed': 9.17,
  'humidity': 79},
 {'city_name': 'Saint Malo',
  'day': '2025-09-15',
  'temp': 14.22,
  'weather': 'clear sky',
  'wind_speed': 8.82,
  'humidity': 83},
 {'city_name': 'Saint Malo',
  'day': '2025-09-15',
  'temp': 14.48,
  'weather': 'broken clouds',
  'wind_speed': 9.41,
  'humidity': 80},
 {'city_name': 'Saint Malo',
  'day': '2025-09-15',
  'temp': 13.92,
  'weather': 'scattered clouds',
  'wind_speed': 8.69,
  'humidity': 78},
 {'city_name': 'Saint Malo',
  'day': '2025-09-15',
  'temp': 16.68,
  'weather': 'light rain',
  'wind_speed': 10.25,
  'humidity': 64},
 {'city_name': 'Saint Malo',
  'day': '2025-09-15',
  'temp': 17.82,
  'weather': 'light rain',
  'wind_speed': 10.34,
  'humidity': 60},
 {'city_name': 'Bayeux',
  'day': '2025-09-10',
  'temp': 17.18,
  'weather': 'overcast clouds',
  'wind_speed': 6.24,
  'humidity': 83},
 {'city_name': 'Bayeux',
  'day': '2025-09-10',
  'temp': 16.52,
  'weather': 'light rain',
  'wind_speed': 9.04,
  'humidity': 89},
 {'city_name': 'Bayeux',
  'day': '2025-09-10',
  'temp': 14.67,
  'weather': 'light rain',
  'wind_speed': 6.43,
  'humidity': 92},
 {'city_name': 'Bayeux',
  'day': '2025-09-11',
  'temp': 13.67,
  'weather': 'few clouds',
  'wind_speed': 5.19,
  'humidity': 93},
 {'city_name': 'Bayeux',
  'day': '2025-09-11',
  'temp': 12.39,
  'weather': 'clear sky',
  'wind_speed': 4.73,
  'humidity': 96},
 {'city_name': 'Bayeux',
  'day': '2025-09-11',
  'temp': 12.04,
  'weather': 'light rain',
  'wind_speed': 6.36,
  'humidity': 95},
 {'city_name': 'Bayeux',
  'day': '2025-09-11',
  'temp': 15.83,
  'weather': 'light rain',
  'wind_speed': 8.07,
  'humidity': 76},
 {'city_name': 'Bayeux',
  'day': '2025-09-11',
  'temp': 16.76,
  'weather': 'light rain',
  'wind_speed': 9.83,
  'humidity': 77},
 {'city_name': 'Bayeux',
  'day': '2025-09-11',
  'temp': 18.92,
  'weather': 'light rain',
  'wind_speed': 9.18,
  'humidity': 47},
 {'city_name': 'Bayeux',
  'day': '2025-09-11',
  'temp': 15.61,
  'weather': 'few clouds',
  'wind_speed': 7.61,
  'humidity': 65},
 {'city_name': 'Bayeux',
  'day': '2025-09-11',
  'temp': 12.27,
  'weather': 'clear sky',
  'wind_speed': 5.78,
  'humidity': 80},
 {'city_name': 'Bayeux',
  'day': '2025-09-12',
  'temp': 10.98,
  'weather': 'light rain',
  'wind_speed': 6.03,
  'humidity': 93},
 {'city_name': 'Bayeux',
  'day': '2025-09-12',
  'temp': 10.81,
  'weather': 'light rain',
  'wind_speed': 5.81,
  'humidity': 93},
 {'city_name': 'Bayeux',
  'day': '2025-09-12',
  'temp': 11.39,
  'weather': 'light rain',
  'wind_speed': 5.72,
  'humidity': 91},
 {'city_name': 'Bayeux',
  'day': '2025-09-12',
  'temp': 15.44,
  'weather': 'light rain',
  'wind_speed': 7.54,
  'humidity': 72},
 {'city_name': 'Bayeux',
  'day': '2025-09-12',
  'temp': 17.52,
  'weather': 'light rain',
  'wind_speed': 8.07,
  'humidity': 59},
 {'city_name': 'Bayeux',
  'day': '2025-09-12',
  'temp': 19.76,
  'weather': 'broken clouds',
  'wind_speed': 7.27,
  'humidity': 43},
 {'city_name': 'Bayeux',
  'day': '2025-09-12',
  'temp': 14.97,
  'weather': 'light rain',
  'wind_speed': 3.73,
  'humidity': 70},
 {'city_name': 'Bayeux',
  'day': '2025-09-12',
  'temp': 12.63,
  'weather': 'light rain',
  'wind_speed': 5.09,
  'humidity': 82},
 {'city_name': 'Bayeux',
  'day': '2025-09-13',
  'temp': 12.72,
  'weather': 'light rain',
  'wind_speed': 5.77,
  'humidity': 88},
 {'city_name': 'Bayeux',
  'day': '2025-09-13',
  'temp': 13.31,
  'weather': 'light rain',
  'wind_speed': 7.75,
  'humidity': 87},
 {'city_name': 'Bayeux',
  'day': '2025-09-13',
  'temp': 12.08,
  'weather': 'light rain',
  'wind_speed': 5.87,
  'humidity': 93},
 {'city_name': 'Bayeux',
  'day': '2025-09-13',
  'temp': 15.18,
  'weather': 'light rain',
  'wind_speed': 7.39,
  'humidity': 82},
 {'city_name': 'Bayeux',
  'day': '2025-09-13',
  'temp': 19.42,
  'weather': 'light rain',
  'wind_speed': 8.75,
  'humidity': 44},
 {'city_name': 'Bayeux',
  'day': '2025-09-13',
  'temp': 18.31,
  'weather': 'broken clouds',
  'wind_speed': 7.94,
  'humidity': 48},
 {'city_name': 'Bayeux',
  'day': '2025-09-13',
  'temp': 15.16,
  'weather': 'scattered clouds',
  'wind_speed': 5.47,
  'humidity': 69},
 {'city_name': 'Bayeux',
  'day': '2025-09-13',
  'temp': 11.45,
  'weather': 'broken clouds',
  'wind_speed': 3.58,
  'humidity': 88},
 {'city_name': 'Bayeux',
  'day': '2025-09-14',
  'temp': 11.23,
  'weather': 'overcast clouds',
  'wind_speed': 4.32,
  'humidity': 86},
 {'city_name': 'Bayeux',
  'day': '2025-09-14',
  'temp': 11.48,
  'weather': 'overcast clouds',
  'wind_speed': 4.81,
  'humidity': 80},
 {'city_name': 'Bayeux',
  'day': '2025-09-14',
  'temp': 13.17,
  'weather': 'light rain',
  'wind_speed': 7.69,
  'humidity': 86},
 {'city_name': 'Bayeux',
  'day': '2025-09-14',
  'temp': 15.83,
  'weather': 'light rain',
  'wind_speed': 10.86,
  'humidity': 86},
 {'city_name': 'Bayeux',
  'day': '2025-09-14',
  'temp': 19.77,
  'weather': 'overcast clouds',
  'wind_speed': 11.51,
  'humidity': 76},
 {'city_name': 'Bayeux',
  'day': '2025-09-14',
  'temp': 24.18,
  'weather': 'overcast clouds',
  'wind_speed': 11.61,
  'humidity': 53},
 {'city_name': 'Bayeux',
  'day': '2025-09-14',
  'temp': 18.26,
  'weather': 'light rain',
  'wind_speed': 10.28,
  'humidity': 87},
 {'city_name': 'Bayeux',
  'day': '2025-09-14',
  'temp': 14.3,
  'weather': 'light rain',
  'wind_speed': 9.79,
  'humidity': 83},
 {'city_name': 'Bayeux',
  'day': '2025-09-15',
  'temp': 13.64,
  'weather': 'few clouds',
  'wind_speed': 8.29,
  'humidity': 82},
 {'city_name': 'Bayeux',
  'day': '2025-09-15',
  'temp': 13.83,
  'weather': 'scattered clouds',
  'wind_speed': 8.11,
  'humidity': 81},
 {'city_name': 'Bayeux',
  'day': '2025-09-15',
  'temp': 13.94,
  'weather': 'light rain',
  'wind_speed': 8.48,
  'humidity': 77},
 {'city_name': 'Bayeux',
  'day': '2025-09-15',
  'temp': 14.54,
  'weather': 'light rain',
  'wind_speed': 8.99,
  'humidity': 74},
 {'city_name': 'Bayeux',
  'day': '2025-09-15',
  'temp': 16.37,
  'weather': 'light rain',
  'wind_speed': 10.69,
  'humidity': 69},
 {'city_name': 'Le Havre',
  'day': '2025-09-10',
  'temp': 17.29,
  'weather': 'light rain',
  'wind_speed': 8.08,
  'humidity': 80},
 {'city_name': 'Le Havre',
  'day': '2025-09-10',
  'temp': 17.08,
  'weather': 'light rain',
  'wind_speed': 9.46,
  'humidity': 85},
 {'city_name': 'Le Havre',
  'day': '2025-09-10',
  'temp': 16.57,
  'weather': 'light rain',
  'wind_speed': 10.14,
  'humidity': 85},
 {'city_name': 'Le Havre',
  'day': '2025-09-11',
  'temp': 15.96,
  'weather': 'light rain',
  'wind_speed': 10.06,
  'humidity': 77},
 {'city_name': 'Le Havre',
  'day': '2025-09-11',
  'temp': 15.38,
  'weather': 'light rain',
  'wind_speed': 8.73,
  'humidity': 77},
 {'city_name': 'Le Havre',
  'day': '2025-09-11',
  'temp': 14.74,
  'weather': 'light rain',
  'wind_speed': 9.62,
  'humidity': 87},
 {'city_name': 'Le Havre',
  'day': '2025-09-11',
  'temp': 16.07,
  'weather': 'light rain',
  'wind_speed': 9.63,
  'humidity': 76},
 {'city_name': 'Le Havre',
  'day': '2025-09-11',
  'temp': 17.53,
  'weather': 'light rain',
  'wind_speed': 11.51,
  'humidity': 72},
 {'city_name': 'Le Havre',
  'day': '2025-09-11',
  'temp': 18.31,
  'weather': 'light rain',
  'wind_speed': 10.13,
  'humidity': 60},
 {'city_name': 'Le Havre',
  'day': '2025-09-11',
  'temp': 17.43,
  'weather': 'few clouds',
  'wind_speed': 9.96,
  'humidity': 62},
 {'city_name': 'Le Havre',
  'day': '2025-09-11',
  'temp': 16.01,
  'weather': 'scattered clouds',
  'wind_speed': 10.05,
  'humidity': 70},
 {'city_name': 'Le Havre',
  'day': '2025-09-12',
  'temp': 14.54,
  'weather': 'light rain',
  'wind_speed': 10.5,
  'humidity': 82},
 {'city_name': 'Le Havre',
  'day': '2025-09-12',
  'temp': 14.23,
  'weather': 'light rain',
  'wind_speed': 9.75,
  'humidity': 83},
 {'city_name': 'Le Havre',
  'day': '2025-09-12',
  'temp': 14.04,
  'weather': 'light rain',
  'wind_speed': 8.72,
  'humidity': 83},
 {'city_name': 'Le Havre',
  'day': '2025-09-12',
  'temp': 15.12,
  'weather': 'light rain',
  'wind_speed': 8.49,
  'humidity': 79},
 {'city_name': 'Le Havre',
  'day': '2025-09-12',
  'temp': 17.2,
  'weather': 'light rain',
  'wind_speed': 9.11,
  'humidity': 65},
 {'city_name': 'Le Havre',
  'day': '2025-09-12',
  'temp': 18.12,
  'weather': 'light rain',
  'wind_speed': 7.86,
  'humidity': 59},
 {'city_name': 'Le Havre',
  'day': '2025-09-12',
  'temp': 17.51,
  'weather': 'light rain',
  'wind_speed': 4.15,
  'humidity': 64},
 {'city_name': 'Le Havre',
  'day': '2025-09-12',
  'temp': 16.94,
  'weather': 'light rain',
  'wind_speed': 6.71,
  'humidity': 65},
 {'city_name': 'Le Havre',
  'day': '2025-09-13',
  'temp': 15.53,
  'weather': 'light rain',
  'wind_speed': 8.32,
  'humidity': 75},
 {'city_name': 'Le Havre',
  'day': '2025-09-13',
  'temp': 14.88,
  'weather': 'light rain',
  'wind_speed': 10.65,
  'humidity': 83},
 {'city_name': 'Le Havre',
  'day': '2025-09-13',
  'temp': 14.76,
  'weather': 'light rain',
  'wind_speed': 9.57,
  'humidity': 85},
 {'city_name': 'Le Havre',
  'day': '2025-09-13',
  'temp': 15.6,
  'weather': 'light rain',
  'wind_speed': 7.98,
  'humidity': 80},
 {'city_name': 'Le Havre',
  'day': '2025-09-13',
  'temp': 17.22,
  'weather': 'light rain',
  'wind_speed': 8.75,
  'humidity': 66},
 {'city_name': 'Le Havre',
  'day': '2025-09-13',

In [14]:
df = pd.DataFrame(forecast_filtered)
df.head()

           city_name         day   temp     weather  wind_speed  humidity
0  Mont Saint Michel  2025-09-10  17.13  light rain        7.07        88
1  Mont Saint Michel  2025-09-10  16.54  light rain        6.37        85
2  Mont Saint Michel  2025-09-10  15.39  light rain        7.33        86
3  Mont Saint Michel  2025-09-11  13.75  light rain        6.32        91
4  Mont Saint Michel  2025-09-11  12.87  light rain        5.36        93

In [15]:
# Convert 'day' column to datetime type to make grouping easier
df['day'] = pd.to_datetime(df['day'])
df.head()

           city_name        day   temp     weather  wind_speed  humidity
0  Mont Saint Michel 2025-09-10  17.13  light rain        7.07        88
1  Mont Saint Michel 2025-09-10  16.54  light rain        6.37        85
2  Mont Saint Michel 2025-09-10  15.39  light rain        7.33        86
3  Mont Saint Michel 2025-09-11  13.75  light rain        6.32        91
4  Mont Saint Michel 2025-09-11  12.87  light rain        5.36        93

In [ ]:
# Grouping by day and calculating statistics
grouped_df = df.groupby(['city_name', 'day']).agg({
    'temp': 'mean',
    'wind_speed': 'mean',
    'humidity': 'mean',
    'weather': lambda x: x.mode()[0]
}).reset_index()

grouped_df

,city_name,day,temp,wind_speed,humidity,weather
0,Aigues Mortes,2025-09-10,24.60000,8.613333,47.333333,broken clouds
1,Aigues Mortes,2025-09-11,21.31875,8.358750,54.375000,clear sky
2,Aigues Mortes,2025-09-12,21.56750,4.831250,62.125000,clear sky
3,Aigues Mortes,2025-09-13,19.48500,3.790000,73.500000,light rain
4,Aigues Mortes,2025-09-14,19.95750,3.716250,63.000000,broken clouds
...,...,...,...,...,...,...
205,Uzes,2025-09-11,20.16250,4.781250,54.625000,clear sky
206,Uzes,2025-09-12,19.99625,2.660000,54.125000,clear sky
207,Uzes,2025-09-13,17.84625,1.692500,71.125000,light rain
208,Uzes,2025-09-14,19.27875,2.801250,56.125000,broken clouds
209,Uzes,2025-09-15,19.81000,1.322000,53.200000,scattered clouds

In [17]:
df_city_data = pd.merge(df_weather_data, grouped_df, on='city_name')

display(df_city_data)

,id,city_name,latitude,longitude,day,temp,wind_speed,humidity,weather
0,29890d50-a6f7-41ad-bd8f-015ec8ecca5c,Mont Saint Michel,48.635954,-1.511460,2025-09-10,16.353333,6.923333,86.333333,light rain
1,29890d50-a6f7-41ad-bd8f-015ec8ecca5c,Mont Saint Michel,48.635954,-1.511460,2025-09-11,14.843750,6.541250,81.000000,light rain
2,29890d50-a6f7-41ad-bd8f-015ec8ecca5c,Mont Saint Michel,48.635954,-1.511460,2025-09-12,15.068750,5.438750,71.875000,few clouds
3,29890d50-a6f7-41ad-bd8f-015ec8ecca5c,Mont Saint Michel,48.635954,-1.511460,2025-09-13,15.392500,5.726250,75.875000,light rain
4,29890d50-a6f7-41ad-bd8f-015ec8ecca5c,Mont Saint Michel,48.635954,-1.511460,2025-09-14,16.430000,8.453750,82.875000,light rain
...,...,...,...,...,...,...,...,...,...
205,79252ffd-b996-451d-9794-fe7ca05c1f90,La Rochelle,46.159732,-1.151595,2025-09-11,17.227500,8.881250,69.500000,light rain
206,79252ffd-b996-451d-9794-fe7ca05c1f90,La Rochelle,46.159732,-1.151595,2025-09-12,17.856250,5.550000,69.375000,light rain
207,79252ffd-b996-451d-9794-fe7ca05c1f90,La Rochelle,46.159732,-1.151595,2025-09-13,18.693750,6.976250,70.375000,light rain
208,79252ffd-b996-451d-9794-fe7ca05c1f90,La Rochelle,46.159732,-1.151595,2025-09-14,19.135000,7.638750,78.875000,broken clouds
209,79252ffd-b996-451d-9794-fe7ca05c1f90,La Rochelle,46.159732,-1.151595,2025-09-15,18.310000,8.368000,71.200000,light rain

In [18]:
df_city_data.to_csv(r"data\cities_data_forecast.csv", index=False)

In [19]:
import plotly.express as px
# https://plotly.com/python/animations/
# https://plotly.github.io/plotly.py-docs/generated/plotly.express.scatter_mapbox.html

df_city_data['day'] = pd.to_datetime(df_city_data['day']).dt.date 

fig = px.scatter_mapbox(df_city_data,
                        lat='latitude',
                        lon='longitude',
                        color='temp',
                        hover_name='city_name',
                        size='temp',
                        animation_frame='day',  # Animate with column 'day'
                        title="City temperatures by day",
                        width=1200,
                        height=900,
                        zoom=5)

fig.update_layout(mapbox_style="open-street-map", 
                  coloraxis_colorbar=dict(title="Temp in °C"  ))
fig.show()

## 1.2 Select 5 top cities with clear skies

In [20]:
weather = df_city_data.get("weather")
print(weather.value_counts())

weather
light rain              76
broken clouds           41
clear sky               35
overcast clouds         31
scattered clouds        18
few clouds               8
heavy intensity rain     1
Name: count, dtype: int64

In [21]:
clear_sky_df = df_city_data[df_city_data['weather'] == 'clear sky']
display(clear_sky_df)

,id,city_name,latitude,longitude,day,temp,wind_speed,humidity,weather
8,dc15a9d5-d9e5-45cc-97a3-2485a4b5188c,Saint Malo,48.649518,-2.026041,2025-09-12,15.75875,7.07625,69.500,clear sky
32,7cef1672-a34e-41c0-a6d7-1260253307ee,Paris,48.858890,2.320041,2025-09-12,17.54000,4.33000,53.000,clear sky
103,2f7c77ce-7156-450c-bffc-ed4ad731edcb,Gorges du Verdon,43.749656,6.328562,2025-09-11,15.79125,3.91625,60.000,clear sky
105,2f7c77ce-7156-450c-bffc-ed4ad731edcb,Gorges du Verdon,43.749656,6.328562,2025-09-13,13.67500,2.19875,67.000,clear sky
109,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-11,21.27375,7.55000,47.875,clear sky
110,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-12,22.07125,6.56750,49.625,clear sky
113,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-15,19.63200,2.01400,74.000,clear sky
115,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-11,20.41125,9.91000,55.750,clear sky
116,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-12,21.52125,6.68500,57.375,clear sky
118,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-14,20.51625,6.02500,61.500,clear sky
121,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-11,21.33750,9.49250,53.625,clear sky
122,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-12,22.49500,6.46250,57.000,clear sky
124,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-14,21.52750,6.50875,59.375,clear sky
127,25256697-856b-4178-bd3a-cd37a089139a,Aix en Provence,43.529842,5.447474,2025-09-11,20.29250,6.33000,47.125,clear sky
128,25256697-856b-4178-bd3a-cd37a089139a,Aix en Provence,43.529842,5.447474,2025-09-12,21.71625,4.10375,47.375,clear sky
133,c0ea9024-87a5-43ad-b895-2b6444607794,Avignon,43.949249,4.805901,2025-09-11,20.99375,4.48125,51.250,clear sky
134,c0ea9024-87a5-43ad-b895-2b6444607794,Avignon,43.949249,4.805901,2025-09-12,20.40500,2.52625,54.375,clear sky
136,c0ea9024-87a5-43ad-b895-2b6444607794,Avignon,43.949249,4.805901,2025-09-14,19.83000,5.13625,55.500,clear sky
139,f7e01925-5dde-45ac-a11e-3fbb4ca6bcd7,Uzes,44.012128,4.419672,2025-09-11,20.16250,4.78125,54.625,clear sky
140,f7e01925-5dde-45ac-a11e-3fbb4ca6bcd7,Uzes,44.012128,4.419672,2025-09-12,19.99625,2.66000,54.125,clear sky
145,7e21bb9e-4fba-4a17-a50f-c05839b358be,Nimes,43.837425,4.360069,2025-09-11,21.33500,4.99250,47.500,clear sky
146,7e21bb9e-4fba-4a17-a50f-c05839b358be,Nimes,43.837425,4.360069,2025-09-12,21.47375,2.62500,49.375,clear sky
148,7e21bb9e-4fba-4a17-a50f-c05839b358be,Nimes,43.837425,4.360069,2025-09-14,20.24750,2.54125,53.000,clear sky
151,e8bc4149-2b80-42ca-a23e-0bee491b74b0,Aigues Mortes,43.566152,4.191540,2025-09-11,21.31875,8.35875,54.375,clear sky
152,e8bc4149-2b80-42ca-a23e-0bee491b74b0,Aigues Mortes,43.566152,4.191540,2025-09-12,21.56750,4.83125,62.125,clear sky
155,e8bc4149-2b80-42ca-a23e-0bee491b74b0,Aigues Mortes,43.566152,4.191540,2025-09-15,20.60600,1.54600,53.200,clear sky
157,2b05944e-c860-40de-b4a8-13639b53d2d2,Saintes Maries de la mer,43.451592,4.427720,2025-09-11,21.22500,9.09625,59.625,clear sky
158,2b05944e-c860-40de-b4a8-13639b53d2d2,Saintes Maries de la mer,43.451592,4.427720,2025-09-12,20.93625,5.89375,67.875,clear sky
161,2b05944e-c860-40de-b4a8-13639b53d2d2,Saintes Maries de la mer,43.451592,4.427720,2025-09-15,20.49800,2.62800,56.600,clear sky
172,033e8575-f70f-4ca0-b827-153851002f8d,Carcassonne,43.213036,2.349107,2025-09-14,19.07750,2.96750,63.500,clear sky
178,ce62a3a3-c13f-4bb7-9c0c-a2553b81cd84,Ariege,42.945537,1.406554,2025-09-14,14.28625,1.80500,73.875,clear sky
184,6554061f-306a-4b83-a1d4-3c802668b174,Toulouse,43.604462,1.444247,2025-09-14,19.03250,1.49125,63.500,clear sky
190,53ef551e-22e8-4f64-9c5e-082e8766ed25,Montauban,44.017584,1.354999,2025-09-14,18.04500,1.45375,67.375,clear sky
196,00321161-2ede-43bc-bdef-1346ba049a39,Biarritz,43.471144,-1.552727,2025-09-14,18.53000,2.12125,69.625,clear sky
202,a1066aad-8212-4a2e-b680-ca607724187b,Bayonne,43.494514,-1.473666,2025-09-14,18.24625,1.99375,70.125,clear sky

In [22]:
clear_sky_count = clear_sky_df['city_name'].value_counts()
print(clear_sky_count)

city_name
Nimes                       3
Bormes les Mimosas          3
Cassis                      3
Marseille                   3
Avignon                     3
Aigues Mortes               3
Saintes Maries de la mer    3
Gorges du Verdon            2
Aix en Provence             2
Uzes                        2
Toulouse                    1
Biarritz                    1
Montauban                   1
Saint Malo                  1
Ariege                      1
Carcassonne                 1
Paris                       1
Bayonne                     1
Name: count, dtype: int64

In [23]:
top_5_cities_clear_sky = clear_sky_count.head(5)
display(top_5_cities_clear_sky)

city_name
Nimes                 3
Bormes les Mimosas    3
Cassis                3
Marseille             3
Avignon               3
Name: count, dtype: int64

In [24]:
top_5_city_names = top_5_cities_clear_sky.index.tolist()
print(top_5_city_names)

['Nimes', 'Bormes les Mimosas', 'Cassis', 'Marseille', 'Avignon']

In [25]:
top_5_clear_sky_df = df_city_data[df_city_data['city_name'].isin(top_5_city_names)]
top_5_clear_sky_df.head(20)

,id,city_name,latitude,longitude,day,temp,wind_speed,humidity,weather
108,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-10,23.073333,8.483333,56.333333,few clouds
109,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-11,21.273750,7.550000,47.875000,clear sky
110,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-12,22.071250,6.567500,49.625000,clear sky
111,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-13,18.021250,2.126250,80.250000,heavy intensity rain
112,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-14,19.571250,2.558750,64.500000,overcast clouds
113,87a31398-1e5b-47b8-a529-b79013bd384a,Bormes les Mimosas,43.150697,6.341928,2025-09-15,19.632000,2.014000,74.000000,clear sky
114,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-10,22.376667,7.853333,58.666667,broken clouds
115,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-11,20.411250,9.910000,55.750000,clear sky
116,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-12,21.521250,6.685000,57.375000,clear sky
117,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-13,19.388750,2.142500,81.125000,broken clouds
118,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-14,20.516250,6.025000,61.500000,clear sky
119,df334f74-b750-4c4a-90ff-b550bdf7915e,Cassis,43.214036,5.539632,2025-09-15,21.100000,1.818000,55.000000,few clouds
120,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-10,23.033333,7.866667,57.000000,few clouds
121,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-11,21.337500,9.492500,53.625000,clear sky
122,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-12,22.495000,6.462500,57.000000,clear sky
123,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-13,20.575000,2.441250,79.000000,light rain
124,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-14,21.527500,6.508750,59.375000,clear sky
125,e38e17cf-5351-4dc6-9ec3-f6d43c063ae9,Marseille,43.296174,5.369953,2025-09-15,22.380000,1.416000,53.000000,scattered clouds
132,c0ea9024-87a5-43ad-b895-2b6444607794,Avignon,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
133,c0ea9024-87a5-43ad-b895-2b6444607794,Avignon,43.949249,4.805901,2025-09-11,20.993750,4.481250,51.250000,clear sky

In [26]:
import plotly.express as px

fig = px.scatter_mapbox(
    top_5_clear_sky_df,
    lat="latitude",         
    lon="longitude",
    color="city_name", 
    size=[10]*len(top_5_clear_sky_df),
    size_max=12,
    hover_name="city_name",
    animation_frame="day",
    title="Top 5 city",
    width=1200,
    height=900,
    zoom=5,
    
)

fig.update_layout(mapbox_style="open-street-map")
fig.show()

## 1.3 Hotel Data

For the hotel data, we will use a scraping script to retrieve the data via the booking.com website ( booking_spyder.py, booking_manager.py ). The script will provide us with a csv file containing the data for the 5 selected cities.

# 2. Data Loading
## 2.1 Upload Data to Data Lake (AWS S3)

In [1]:
!pip install Boto3

Requirement already satisfied: Boto3 in c:\users\typhon\anaconda3\lib\site-packages (1.35.38)
Requirement already satisfied: botocore<1.36.0,>=1.35.38 in c:\users\typhon\anaconda3\lib\site-packages (from Boto3) (1.35.38)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\typhon\anaconda3\lib\site-packages (from Boto3) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in c:\users\typhon\anaconda3\lib\site-packages (from Boto3) (0.10.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\typhon\anaconda3\lib\site-packages (from botocore<1.36.0,>=1.35.38->Boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\typhon\anaconda3\lib\site-packages (from botocore<1.36.0,>=1.35.38->Boto3) (2.2.2)
Requirement already satisfied: six>=1.5 in c:\users\typhon\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.36.0,>=1.35.38->Boto3) (1.16.0)

In [2]:
from dotenv import load_dotenv
import os
import boto3

In [3]:
load_dotenv()

True

In [4]:
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
BUCKET_NAME = os.getenv("BUCKET_NAME")

In [15]:
session = boto3.Session(aws_access_key_id=AWS_ACCESS_KEY_ID, 
                        aws_secret_access_key=AWS_SECRET_ACCESS_KEY)

In [16]:
s3 = session.resource("s3")

In [17]:
bucket = s3.Bucket(BUCKET_NAME)

In [18]:
bucket.upload_file("data/cities_data_forecast.csv", "cities_data_forecast.csv")

In [19]:
bucket.upload_file("data/all_cities.csv", "cities_data_hotels.csv")

## 2.2 Load Data from AWS S3 to AWS RDS

In [10]:
import pandas as pd

In [6]:
## Libraries to install if other connections than sqlite

## For MySQL engines
## !pip install pymysql 
## For PostgreSQL engines
!pip install psycopg2-binary 
!pip install sqlalchemy==2.0.0

Requirement already satisfied: psycopg2-binary in c:\users\typhon\anaconda3\lib\site-packages (2.9.9)
Requirement already satisfied: sqlalchemy==2.0.0 in c:\users\typhon\anaconda3\lib\site-packages (2.0.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\typhon\anaconda3\lib\site-packages (from sqlalchemy==2.0.0) (4.13.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\typhon\anaconda3\lib\site-packages (from sqlalchemy==2.0.0) (3.2.4)

In [7]:
DB_USER =  os.getenv("DB_USER")
DB_PASS =  os.getenv("DB_PASS")
DB_HOST =  os.getenv("DB_HOST")
DB_PORT =   os.getenv("DB_PORT")
DB_NAME =  os.getenv("DB_NAME")

In [24]:
# Namefiles of data stored in S3
FILES = ["cities_data_forecast.csv", "cities_data_hotels.csv"]

In [ ]:
# Get data from S3
for file in FILES:
    bucket.download_file(file, file)
    print(f"{file} téléchargé depuis S3")

cities_data_forecast.csv téléchargé depuis S3
cities_data_hotels.csv téléchargé depuis S3

In [11]:
df_meteo = pd.read_csv("cities_data_forecast.csv")
df_hotels = pd.read_csv("cities_data_hotels.csv")

print(df_meteo.head())
print(df_hotels.head())

                                     id          city_name   latitude  \
0  29890d50-a6f7-41ad-bd8f-015ec8ecca5c  Mont Saint Michel  48.635954
1  29890d50-a6f7-41ad-bd8f-015ec8ecca5c  Mont Saint Michel  48.635954
2  29890d50-a6f7-41ad-bd8f-015ec8ecca5c  Mont Saint Michel  48.635954
3  29890d50-a6f7-41ad-bd8f-015ec8ecca5c  Mont Saint Michel  48.635954
4  29890d50-a6f7-41ad-bd8f-015ec8ecca5c  Mont Saint Michel  48.635954

   longitude         day       temp  wind_speed   humidity     weather
0   -1.51146  2025-09-10  16.353333    6.923333  86.333333  light rain
1   -1.51146  2025-09-11  14.843750    6.541250  81.000000  light rain
2   -1.51146  2025-09-12  15.068750    5.438750  71.875000  few clouds
3   -1.51146  2025-09-13  15.392500    5.726250  75.875000  light rain
4   -1.51146  2025-09-14  16.430000    8.453750  82.875000  light rain
      city                                              hotel  \
0  Avignon                                   Hôtel Le Bristol
1  Avignon                         Appartement Les Hortensias
2  Avignon  Apartment-NO elevator-Free private parking-Sel...
3  Avignon                      Garlande Hôtel Avignon Centre
4  Avignon                                 Hôtel de l'Horloge

                                             address  rating  reviews  \
0        44 Cours Jean Jaurès, 84000 Avignon, France     8.3     5006
1  20, Boulevard de la Liberté, 84000 Avignon, Fr...     9.3       56
2          170 Rue Carreterie, 84000 Avignon, France     9.7      148
3              20 Rue Galante, 84000 Avignon, France     8.9      700
4  1 Rue Félicien David - Place de l'Horloge, 840...     8.4     1345

                                                 url  \
0  https://www.booking.com/hotel/fr/hotel-bristol...
1  https://www.booking.com/hotel/fr/les-hortensia...
2  https://www.booking.com/hotel/fr/intramuros-pa...
3  https://www.booking.com/hotel/fr/de-garlande.f...
4  https://www.booking.com/hotel/fr/de-l-horloge....

                                         description   latitude  longitude
0  Idéalement situé à l’intérieur des remparts du...  43.944032   4.805332
1  Situé à 10 minutes à pied du centre d'Avignon ...  43.943377   4.819127
2  L’hébergement Apartment-NO elevator-Free priva...  43.950923   4.818413
3  Doté d’une connexion Wi-Fi gratuite, le Garlan...  43.947618   4.806804
4  L'Hôtel de l'Horloge occupe un bâtiment du XIX...  43.948967   4.805472

In [12]:
# Normalize column name for city
df_hotels.rename(columns={"city": "city_name"}, inplace=True)

In [13]:
display(df_hotels)

,city_name,hotel,address,rating,reviews,url,description,latitude,longitude
0,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332
1,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127
2,Avignon,Apartment-NO elevator-Free private parking-Sel...,"170 Rue Carreterie, 84000 Avignon, France",9.7,148,https://www.booking.com/hotel/fr/intramuros-pa...,L’hébergement Apartment-NO elevator-Free priva...,43.950923,4.818413
3,Avignon,Garlande Hôtel Avignon Centre,"20 Rue Galante, 84000 Avignon, France",8.9,700,https://www.booking.com/hotel/fr/de-garlande.f...,"Doté d’une connexion Wi-Fi gratuite, le Garlan...",43.947618,4.806804
4,Avignon,Hôtel de l'Horloge,"1 Rue Félicien David - Place de l'Horloge, 840...",8.4,1345,https://www.booking.com/hotel/fr/de-l-horloge....,L'Hôtel de l'Horloge occupe un bâtiment du XIX...,43.948967,4.805472
...,...,...,...,...,...,...,...,...,...
120,Nîmes,ibis Nîmes Ouest - A9,"268, Rue de l'Hostellerie / Parc Hotelier Vill...",8.2,2246,https://www.booking.com/hotel/fr/ibis-na-r-mes...,Situé à côté de la sortie 25 sur l’autoroute A...,43.813891,4.344342
121,Nîmes,Hôtel & Spa Vatel,"140, rue Vatel, 30900 Nîmes, France",8.4,1096,https://www.booking.com/hotel/fr/vatel.fr.html,L’Hôtel & Spa Vatel vous accueille à 10 minute...,43.820577,4.319127
122,Nîmes,Maison Albar Hotels L’Imperator,"15 Rue Gaston Boissier, 30900 Nîmes, France",9.1,1323,https://www.booking.com/hotel/fr/imperator-nim...,La Maison Albar Hotels L’Imperator est un hôte...,43.838666,4.352768
123,Nîmes,Campanile PRIME - Nîmes Centre,"45 Rue San-Lucar, Zac Du Mas-Carbonnel, 30900 ...",8.0,680,https://www.booking.com/hotel/fr/campanile-nim...,"Situé à Nîmes, l’établissement 3 étoiles Campa...",43.822731,4.364126
124,Nîmes,Appart'hôtel Odalys City - Nîmes Arènes - Pala...,"4 Rue Alexandre Ducros, 30000 Nîmes, France",8.5,2662,https://www.booking.com/hotel/fr/odalys-city-n...,L’établissement Appart'hôtel Odalys City - Nîm...,43.834062,4.358991

In [14]:
# Normalize city name
city_corrections = {
    "Nîmes": "Nimes",
    "Bormes-les-Mimosas": "Bormes les Mimosas"
}

In [15]:
df_hotels["city_name"] = df_hotels["city_name"].replace(city_corrections)

In [35]:
display(df_hotels)

,city_name,hotel,address,rating,reviews,url,description,latitude,longitude
0,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332
1,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127
2,Avignon,Apartment-NO elevator-Free private parking-Sel...,"170 Rue Carreterie, 84000 Avignon, France",9.7,148,https://www.booking.com/hotel/fr/intramuros-pa...,L’hébergement Apartment-NO elevator-Free priva...,43.950923,4.818413
3,Avignon,Garlande Hôtel Avignon Centre,"20 Rue Galante, 84000 Avignon, France",8.9,700,https://www.booking.com/hotel/fr/de-garlande.f...,"Doté d’une connexion Wi-Fi gratuite, le Garlan...",43.947618,4.806804
4,Avignon,Hôtel de l'Horloge,"1 Rue Félicien David - Place de l'Horloge, 840...",8.4,1345,https://www.booking.com/hotel/fr/de-l-horloge....,L'Hôtel de l'Horloge occupe un bâtiment du XIX...,43.948967,4.805472
...,...,...,...,...,...,...,...,...,...
120,Nimes,ibis Nîmes Ouest - A9,"268, Rue de l'Hostellerie / Parc Hotelier Vill...",8.2,2246,https://www.booking.com/hotel/fr/ibis-na-r-mes...,Situé à côté de la sortie 25 sur l’autoroute A...,43.813891,4.344342
121,Nimes,Hôtel & Spa Vatel,"140, rue Vatel, 30900 Nîmes, France",8.4,1096,https://www.booking.com/hotel/fr/vatel.fr.html,L’Hôtel & Spa Vatel vous accueille à 10 minute...,43.820577,4.319127
122,Nimes,Maison Albar Hotels L’Imperator,"15 Rue Gaston Boissier, 30900 Nîmes, France",9.1,1323,https://www.booking.com/hotel/fr/imperator-nim...,La Maison Albar Hotels L’Imperator est un hôte...,43.838666,4.352768
123,Nimes,Campanile PRIME - Nîmes Centre,"45 Rue San-Lucar, Zac Du Mas-Carbonnel, 30900 ...",8.0,680,https://www.booking.com/hotel/fr/campanile-nim...,"Situé à Nîmes, l’établissement 3 étoiles Campa...",43.822731,4.364126
124,Nimes,Appart'hôtel Odalys City - Nîmes Arènes - Pala...,"4 Rue Alexandre Ducros, 30000 Nîmes, France",8.5,2662,https://www.booking.com/hotel/fr/odalys-city-n...,L’établissement Appart'hôtel Odalys City - Nîm...,43.834062,4.358991

In [16]:
# Merged data with city name
df_final = pd.merge(
    df_hotels,
    df_meteo,
    on="city_name",
    how="left"
)

In [17]:
df_final.head(10)

,city_name,hotel,address,rating,reviews,url,description,latitude_x,longitude_x,id,latitude_y,longitude_y,day,temp,wind_speed,humidity,weather
0,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
1,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-11,20.993750,4.481250,51.250000,clear sky
2,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-12,20.405000,2.526250,54.375000,clear sky
3,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds
4,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-14,19.830000,5.136250,55.500000,clear sky
5,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-15,19.576000,1.632000,50.600000,scattered clouds
6,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
7,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-11,20.993750,4.481250,51.250000,clear sky
8,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-12,20.405000,2.526250,54.375000,clear sky
9,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds

In [21]:
from sqlalchemy import create_engine

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/postgres"
)

In [22]:
# Create database
df_final.to_sql("hotels_forecast", engine, if_exists="replace", index=False)
print("Table created in AWS RDS !")

Table created in AWS RDS !

In [ ]:
# Check if the table are stored in database
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='public';"))
    print("📋 Tables présentes dans la base :")
    for row in result:
        print(row[0])

📋 Tables présentes dans la base :
hotels_forecast

In [26]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM hotels_forecast LIMIT 5;"))
    for row in result:
        print(row)

('Avignon', 'Hôtel Le Bristol', '44 Cours Jean Jaurès, 84000 Avignon, France', 8.3, 5006, 'https://www.booking.com/hotel/fr/hotel-bristol-avignon.fr.html', 'Idéalement situé à l’intérieur des remparts du centre d’Avignon, l’Hôtel Le Bristol vous propose des chambres climatisées, un bar, une connexion Wi-Fi...', 43.9440321, 4.8053317, 'c0ea9024-87a5-43ad-b895-2b6444607794', 43.9492493, 4.8059012, '2025-09-10', 23.96666666666667, 4.546666666666667, 46.333333333333336, 'scattered clouds')
('Avignon', 'Hôtel Le Bristol', '44 Cours Jean Jaurès, 84000 Avignon, France', 8.3, 5006, 'https://www.booking.com/hotel/fr/hotel-bristol-avignon.fr.html', 'Idéalement situé à l’intérieur des remparts du centre d’Avignon, l’Hôtel Le Bristol vous propose des chambres climatisées, un bar, une connexion Wi-Fi...', 43.9440321, 4.8053317, 'c0ea9024-87a5-43ad-b895-2b6444607794', 43.9492493, 4.8059012, '2025-09-11', 20.99375, 4.48125, 51.25, 'clear sky')
('Avignon', 'Hôtel Le Bristol', '44 Cours Jean Jaurès, 84000 Avignon, France', 8.3, 5006, 'https://www.booking.com/hotel/fr/hotel-bristol-avignon.fr.html', 'Idéalement situé à l’intérieur des remparts du centre d’Avignon, l’Hôtel Le Bristol vous propose des chambres climatisées, un bar, une connexion Wi-Fi...', 43.9440321, 4.8053317, 'c0ea9024-87a5-43ad-b895-2b6444607794', 43.9492493, 4.8059012, '2025-09-12', 20.405, 2.52625, 54.375, 'clear sky')
('Avignon', 'Hôtel Le Bristol', '44 Cours Jean Jaurès, 84000 Avignon, France', 8.3, 5006, 'https://www.booking.com/hotel/fr/hotel-bristol-avignon.fr.html', 'Idéalement situé à l’intérieur des remparts du centre d’Avignon, l’Hôtel Le Bristol vous propose des chambres climatisées, un bar, une connexion Wi-Fi...', 43.9440321, 4.8053317, 'c0ea9024-87a5-43ad-b895-2b6444607794', 43.9492493, 4.8059012, '2025-09-13', 18.215, 2.01875, 71.375, 'broken clouds')
('Avignon', 'Hôtel Le Bristol', '44 Cours Jean Jaurès, 84000 Avignon, France', 8.3, 5006, 'https://www.booking.com/hotel/fr/hotel-bristol-avignon.fr.html', 'Idéalement situé à l’intérieur des remparts du centre d’Avignon, l’Hôtel Le Bristol vous propose des chambres climatisées, un bar, une connexion Wi-Fi...', 43.9440321, 4.8053317, 'c0ea9024-87a5-43ad-b895-2b6444607794', 43.9492493, 4.8059012, '2025-09-14', 19.83, 5.13625, 55.5, 'clear sky')

In [31]:
from sqlalchemy import text
import pandas as pd

with engine.connect() as conn:
    query = text("""
        SELECT DISTINCT ON (hotel) *
        FROM hotels_forecast
        WHERE city_name = 'Avignon'
        ORDER BY hotel, rating DESC
        LIMIT 20;
    """)
    df_avignon = pd.read_sql(query, conn)

df_avignon

,city_name,hotel,address,rating,reviews,url,description,latitude_x,longitude_x,id,latitude_y,longitude_y,day,temp,wind_speed,humidity,weather
0,Avignon,ApartHotel Sainte-Marthe,"6 Route de Lyon , 84000 Avignon, France",8.0,6008,https://www.booking.com/hotel/fr/ra-c-sidence-...,Enjoy a comfortable stay at Apart’Hotel Sainte...,43.949895,4.819864,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
1,Avignon,Apartment 40m2-Air conditioning-Elevator-Under...,"3 Rue Velouterie, 84000 Avignon, France",9.7,109,https://www.booking.com/hotel/fr/appart-parkin...,L’hébergement Apartment 40m2-Air conditioning-...,43.945188,4.799626,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
2,Avignon,Apartment-NO elevator-Free private parking-Sel...,"170 Rue Carreterie, 84000 Avignon, France",9.7,148,https://www.booking.com/hotel/fr/intramuros-pa...,L’hébergement Apartment-NO elevator-Free priva...,43.950923,4.818413,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
3,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-15,19.576000,1.632000,50.600000,scattered clouds
4,Avignon,"Au cœur des Papes, dans bâtisse de charme stud...","5 Rue et Place Noël Antoine Biret, 84000 Avign...",8.0,734,https://www.booking.com/hotel/fr/au-coeur-des-...,Proposant une terrasse et une connexion Wi-Fi ...,43.946171,4.810189,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds
5,Avignon,Avignon Grand Hotel,"34, bd Saint-Roch, 84000 Avignon, France",8.2,3016,https://www.booking.com/hotel/fr/avignongrandh...,"Doté d'une petite piscine sur le toit, l'Avign...",43.942545,4.804362,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
6,Avignon,Best Western Plus Le Lavarin,"1715 Chemin du Lavarin, 84000 Avignon, France",8.3,2193,https://www.booking.com/hotel/fr/hotellelavari...,L’hôtel Best Western Plus Le Lavarin est situé...,43.922758,4.804295,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
7,Avignon,Garlande Hôtel Avignon Centre,"20 Rue Galante, 84000 Avignon, France",8.9,700,https://www.booking.com/hotel/fr/de-garlande.f...,"Doté d’une connexion Wi-Fi gratuite, le Garlan...",43.947618,4.806804,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-15,19.576000,1.632000,50.600000,scattered clouds
8,Avignon,Hôtel Central,"31/33 Rue De La République, 84000 Avignon, France",7.9,2656,https://www.booking.com/hotel/fr/central-avign...,"Situé au cœur de la vieille ville d'Avignon, l...",43.945525,4.805761,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
9,Avignon,Hôtel Cloitre Saint Louis Avignon,"20, rue du Portail Boquier, 84000 Avignon, France",7.6,3355,https://www.booking.com/hotel/fr/clarioncloitr...,"Situé dans le centre d'Avignon, à 15 minutes à...",43.943808,4.804947,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-11,20.993750,4.481250,51.250000,clear sky
10,Avignon,Hotel De Cambis Best Western Premier Collection,"89 Rue Joseph Vernet, 84000 Avignon, France",8.7,757,https://www.booking.com/hotel/fr/de-cambis-bw-...,L’établissement Hotel De Cambis Best Western P...,43.947113,4.803330,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds
11,Avignon,Hôtel de l'Horloge,"1 Rue Félicien David - Place de l'Horloge, 840...",8.4,1345,https://www.booking.com/hotel/fr/de-l-horloge....,L'Hôtel de l'Horloge occupe un bâtiment du XIX...,43.948967,4.805472,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
12,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-11,20.993750,4.481250,51.250000,clear sky
13,Avignon,Hotel Le Magnan,"63 Rue du Portail Magnanen, 84000 Avignon, France",8.4,2492,https://www.booking.com/hotel/fr/hotellemagnan...,Situé dans un cadre verdoyant au sein des anci...,43.943630,4.812171,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
14,Avignon,Hôtel Le Médiéval Palais des Papes,"15 rue Petite Saunerie, 84000 Avignon, France",8.0,1440,https://www.booking.com/hotel/fr/le-medieval-a...,L'Hôtel Le Médiéval Palais des Papes occupe l'...,43.949306,4.809346,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
15,Avignon,ibis Avignon Centre Gare,"42 boulevard Saint Roch, 84000 Avignon, France",7.7,1126,https://www.booking.com/hotel/fr/ibis-avignon-...,L'ibis Avignon Centre Gare est situé au cœur d...,43.942291,4.807274,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds
16,Avignon,ibis Styles Avignon Sud,"2968 avenue de l'Amandier, 84000 Avignon, France",8.3,2656,https://www.booking.com/hotel/fr/avignon.fr.html,L'ibis Styles Avignon Sud se situe à 4 km des ...,43.926166,4.844421,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-15,19.576000,1.632000,50.600000,scattered clouds
17,Avignon,Kyriad Avignon - Palais des Papes,"26, Place de l'horloge, 84000 Avignon, France",8.4,2594,https://www.booking.com/hotel/fr/kyriad-avigno...,"Located on Place de l'Horloge, the Kyriad Pala...",43.949638,4.806359,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds
18,Avignon,La Chapelle du Miracle,"13 rue velouterie, 84000 Avignon, France",9.0,499,https://www.booking.com/hotel/fr/chapelle-du-m...,"Situé à Avignon, l'établissement La Chapelle d...",43.944483,4.799496,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-12,20.405000,2.526250,54.375000,clear sky
19,Avignon,Lavande Dorée,"13B Rue Bon Martinet, 84000 Avignon, France",9.4,33,https://www.booking.com/hotel/fr/lavande-doree...,L’hébergement Lavande Dorée affiche 3 étoiles ...,43.944341,4.812729,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-15,19.576000,1.632000,50.600000,scattered clouds

In [ ]:
with engine.connect() as conn:
    query = text("SELECT * FROM hotels_forecast;")
    df_local = pd.read_sql(query, conn)

# Save in CSV file
df_local.to_csv("hotels_forecast_local.csv", index=False)

# 3. Display visualization

In [10]:
import pandas as pd
import plotly.graph_objects as go
from math import cos, radians

In [3]:
# load local data from hotels_forecast_local.csv
df_global = pd.read_csv("hotels_forecast_local.csv")

## 3.1 Display Weather in 5 top areas

In [4]:
# For weather map we don't need hotels info => delete hotels info
df_forecast = df_global.drop(["hotel","address","rating","reviews","url","description","latitude_x","longitude_x"], axis=1)
# Rename latitude et longitude
df_forecast = df_forecast.rename(columns={'latitude_y': 'latitude', 'longitude_y': 'longitude'})

In [5]:
df_forecast.head()

,city_name,id,latitude,longitude,day,temp,wind_speed,humidity,weather
0,Avignon,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
1,Avignon,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-11,20.993750,4.481250,51.250000,clear sky
2,Avignon,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-12,20.405000,2.526250,54.375000,clear sky
3,Avignon,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds
4,Avignon,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-14,19.830000,5.136250,55.500000,clear sky

In [6]:
# Create mapping icon to display on the map
icon_map = {
    "clear sky": "https://img.icons8.com/emoji/96/sun-emoji.png",
    "few clouds": "https://img.icons8.com/emoji/96/cloud-emoji.png",
    "scattered clouds": "https://img.icons8.com/emoji/96/cloud-emoji.png",
    "broken clouds": "https://img.icons8.com/fluency/96/clouds--v3.png",
    "overcast clouds": "https://img.icons8.com/fluency/96/clouds--v3.png",
    "shower rain": "https://img.icons8.com/emoji/96/cloud-with-rain-emoji.png",
    "light rain": "https://img.icons8.com/emoji/96/cloud-with-rain-emoji.png",
    "heavy intensity rain": "https://img.icons8.com/color/96/intense-rain--v1.png",
    "rain": "https://img.icons8.com/color/96/intense-rain--v1.png",
    "thunderstorm": "https://img.icons8.com/emoji/96/cloud-with-lightning-and-rain.png",
    "snow": "https://img.icons8.com/emoji/96/snowflake-emoji.png",
    "mist": "https://img.icons8.com/emoji/96/fog.png"
}

In [7]:
# Create new column with mapping icon
df_forecast['icon_url'] = df_forecast['weather'].map(icon_map).fillna("https://img.icons8.com/ios-glyphs/30/question-mark.png")

In [12]:
def bbox_for_point(lon, lat, km=25):
    """Return mapbox coordinates for image box.
       Mapbox expects order: Top-Left, Top-Right, Bottom-Right, Bottom-Left"""
    lat_deg = km / 110.574
    lon_deg = km / (111.320 * cos(radians(lat)))
    return [
        [lon - lon_deg, lat + lat_deg],  # Top-Left
        [lon + lon_deg, lat + lat_deg],  # Top-Right
        [lon + lon_deg, lat - lat_deg],  # Bottom-Right
        [lon - lon_deg, lat - lat_deg],  # Bottom-Left
    ]

def make_layers(df_subset, km=25):
    layers = []
    for _, r in df_subset.iterrows():
        layers.append({
            "sourcetype": "image",
            "source": r["icon_url"],
            "coordinates": bbox_for_point(r["longitude"], r["latitude"], km=km)
        })
    return layers

In [14]:
## Make figure & frames

days = sorted(df_forecast['day'].unique())
if len(days) == 0:
    raise ValueError("Aucune date trouvée dans df_forecast['day']")

# Choose non-empty day0 for initial display
first_day = next((d for d in days if not df_forecast[df_forecast['day']==d].empty), days[0])
df_forecast0 = df_forecast[df_forecast['day'] == first_day]

fig = go.Figure()

# "invisible" trace needed to display the map and provide hover points
fig.add_trace(go.Scattermapbox(
    lat=df_forecast0["latitude"],
    lon=df_forecast0["longitude"],
    mode="markers",
    # invisible but hoverable markers: size not zero, color transparent
    marker=dict(size=18, color="rgba(0,0,0,0)"),
    text=df_forecast0["city_name"],
    hovertemplate="%{text}<extra></extra>",
    showlegend=False
))

# Layout initial: 
fig.update_layout(
    mapbox_style="carto-darkmatter",
    mapbox_layers=make_layers(df_forecast0, km=25),
    mapbox_center={"lat": 46.6, "lon": 2.2},
    mapbox_zoom=5,
    width=1200, height=800,
    title="Météo (icônes) — animation"
)

# Build frames : each frame contains the trace of hover + layout (layers + center + zoom)
frames = []
for day in days:
    d = df_forecast[df_forecast['day'] == day]
    # trace : same points (invisible) but with text = city_name for the hover
    trace = go.Scattermapbox(
        lat=d["latitude"],
        lon=d["longitude"],
        mode="markers",
        marker=dict(size=36, color="rgba(0,0,0,0)"),
        text=d["city_name"],
        hovertemplate="%{text}<extra></extra>",
        showlegend=False
    )
    frame_layout = go.Layout(mapbox=dict(layers=make_layers(d, km=25)))
    frames.append(go.Frame(name=day, data=[trace], layout=frame_layout))

fig.frames = frames

# controls
fig.update_layout(
    updatemenus=[{
        "type": "buttons",
        "buttons": [{
            "label": "▶ Play",
            "method": "animate",
            "args": [None, {"frame": {"duration": 800, "redraw": True}, "fromcurrent": True}]
        }]
    }],
    sliders=[{
        "active": 0,
        "currentvalue": {"prefix": "Jour : "},
        "pad": {"t": 40},
        "steps": [{
            "args": [[d], {"frame": {"duration": 0, "redraw": True}, "mode": "immediate"}],
            "label": d,
            "method": "animate"
        } for d in days]
    }]
)

fig.show()
fig.write_html("top-5-city.html", auto_open=True)

## 3.2 Display 20 hotels per city

In [15]:
df_global.head(10)

,city_name,hotel,address,rating,reviews,url,description,latitude_x,longitude_x,id,latitude_y,longitude_y,day,temp,wind_speed,humidity,weather
0,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
1,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-11,20.993750,4.481250,51.250000,clear sky
2,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-12,20.405000,2.526250,54.375000,clear sky
3,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds
4,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-14,19.830000,5.136250,55.500000,clear sky
5,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-15,19.576000,1.632000,50.600000,scattered clouds
6,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-10,23.966667,4.546667,46.333333,scattered clouds
7,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-11,20.993750,4.481250,51.250000,clear sky
8,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-12,20.405000,2.526250,54.375000,clear sky
9,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127,c0ea9024-87a5-43ad-b895-2b6444607794,43.949249,4.805901,2025-09-13,18.215000,2.018750,71.375000,broken clouds

In [16]:
# Remove duplicates, we no longer need weather data, we can delete these columns
df_unique = df_global.drop_duplicates(subset=["hotel", "city_name"])
df_unique = df_unique.drop(["id","latitude_y","longitude_y","day","temp","wind_speed","humidity","weather"], axis=1)

In [17]:
df_unique.head(10)

,city_name,hotel,address,rating,reviews,url,description,latitude_x,longitude_x
0,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332
6,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127
12,Avignon,Apartment-NO elevator-Free private parking-Sel...,"170 Rue Carreterie, 84000 Avignon, France",9.7,148,https://www.booking.com/hotel/fr/intramuros-pa...,L’hébergement Apartment-NO elevator-Free priva...,43.950923,4.818413
15,Avignon,Novotel Avignon Centre,"20 boulevard Saint Roch, 84000 Avignon, France",7.9,885,https://www.booking.com/hotel/fr/novotel-avign...,Installé à côté de la gare ferroviaire d’Avign...,43.942735,4.802436
19,Avignon,Garlande Hôtel Avignon Centre,"20 Rue Galante, 84000 Avignon, France",8.9,700,https://www.booking.com/hotel/fr/de-garlande.f...,"Doté d’une connexion Wi-Fi gratuite, le Garlan...",43.947618,4.806804
25,Avignon,Hôtel de l'Horloge,"1 Rue Félicien David - Place de l'Horloge, 840...",8.4,1345,https://www.booking.com/hotel/fr/de-l-horloge....,L'Hôtel de l'Horloge occupe un bâtiment du XIX...,43.948967,4.805472
36,Avignon,Apartment 40m2-Air conditioning-Elevator-Under...,"3 Rue Velouterie, 84000 Avignon, France",9.7,109,https://www.booking.com/hotel/fr/appart-parkin...,L’hébergement Apartment 40m2-Air conditioning-...,43.945188,4.799626
42,Avignon,"Au cœur des Papes, dans bâtisse de charme stud...","5 Rue et Place Noël Antoine Biret, 84000 Avign...",8.0,734,https://www.booking.com/hotel/fr/au-coeur-des-...,Proposant une terrasse et une connexion Wi-Fi ...,43.946171,4.810189
48,Avignon,Hôtel Central,"31/33 Rue De La République, 84000 Avignon, France",7.9,2656,https://www.booking.com/hotel/fr/central-avign...,"Situé au cœur de la vieille ville d'Avignon, l...",43.945525,4.805761
54,Avignon,ApartHotel Sainte-Marthe,"6 Route de Lyon , 84000 Avignon, France",8.0,6008,https://www.booking.com/hotel/fr/ra-c-sidence-...,Enjoy a comfortable stay at Apart’Hotel Sainte...,43.949895,4.819864

In [18]:
# Rename latitude et longitude
df_unique = df_unique.rename(columns={'latitude_x': 'latitude', 'longitude_x': 'longitude'})

In [19]:
df_unique.head(5)

,city_name,hotel,address,rating,reviews,url,description,latitude,longitude
0,Avignon,Hôtel Le Bristol,"44 Cours Jean Jaurès, 84000 Avignon, France",8.3,5006,https://www.booking.com/hotel/fr/hotel-bristol...,Idéalement situé à l’intérieur des remparts du...,43.944032,4.805332
6,Avignon,Appartement Les Hortensias,"20, Boulevard de la Liberté, 84000 Avignon, Fr...",9.3,56,https://www.booking.com/hotel/fr/les-hortensia...,Situé à 10 minutes à pied du centre d'Avignon ...,43.943377,4.819127
12,Avignon,Apartment-NO elevator-Free private parking-Sel...,"170 Rue Carreterie, 84000 Avignon, France",9.7,148,https://www.booking.com/hotel/fr/intramuros-pa...,L’hébergement Apartment-NO elevator-Free priva...,43.950923,4.818413
15,Avignon,Novotel Avignon Centre,"20 boulevard Saint Roch, 84000 Avignon, France",7.9,885,https://www.booking.com/hotel/fr/novotel-avign...,Installé à côté de la gare ferroviaire d’Avign...,43.942735,4.802436
19,Avignon,Garlande Hôtel Avignon Centre,"20 Rue Galante, 84000 Avignon, France",8.9,700,https://www.booking.com/hotel/fr/de-garlande.f...,"Doté d’une connexion Wi-Fi gratuite, le Garlan...",43.947618,4.806804

In [20]:
# Select only 20 top hotels
df_top_hotels = (
    df_unique.sort_values(["city_name", "rating"], ascending=[True, False])
    .groupby("city_name")
    .head(20)
    .reset_index(drop=True)
)

In [32]:
# Wrapped description data to avoid long tooltip
import textwrap

df_top_hotels["description_wrapped"] = df_top_hotels["description"].apply(
    lambda d: "<br>".join(textwrap.wrap(str(d), width=80)) if pd.notnull(d) else ""
)
df_top_hotels["hotel_name_wrapped"] = df_top_hotels["hotel"].apply(
    lambda d: "<br>".join(textwrap.wrap(str(d), width=80)) if pd.notnull(d) else ""
)

In [ ]:
# Display map with top hotels
fig = px.scatter_mapbox(
    df_top_hotels,
    lat="latitude",
    lon="longitude",
    color="city_name",
    size="rating",
    custom_data=["hotel_name_wrapped", "rating", "address", "description_wrapped"],
    zoom=5,
    height=800
)

fig.update_traces(
    hovertemplate=(
        "<b>%{customdata[0]}</b> <br><br>"           
        "Adresse: %{customdata[2]}<br>"
        "Note: %{customdata[1]} ⭐<br><br>"               
        "<b>%{customdata[3]}</b>"                     
        "<extra></extra>"
    )
)

fig.update_layout(
    mapbox_style="open-street-map",
    margin={"r":0,"t":0,"l":0,"b":0}
)
fig.show()
fig.write_html("20_hotels_in_area.html", auto_open=True)